
/*
    This file was automatically generated by utility contrib/unicode/ucd.lisp
    for Unicode "6.2.0"

    Copyright (c) 2012, Jean-Claude Beaudoin.

    MKCL is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 3 of the License, or (at your option) any later version.

    See file '../../Copyright' for full details.
*/

#ifndef MKCL_UNICODE_H
#define MKCL_UNICODE_H

#define MKCL_UNICHAR_INVALID_DIGIT ((mkcl_uint8_t) 255)


enum mkcl_ucd_general_category {
  mkcl_ucd_Uppercase_Letter,
  mkcl_ucd_Lowercase_Letter,
  mkcl_ucd_Titlecase_Letter,
  mkcl_ucd_Modified_Letter,
  mkcl_ucd_Other_Letter,
  mkcl_ucd_Control,
  mkcl_ucd_Format,
  mkcl_ucd_Private_Use,
  mkcl_ucd_Surrogate,
  mkcl_ucd_Spacing_Mark,
  mkcl_ucd_Enclosing_Mark,
  mkcl_ucd_Nonspacing_Mark,
  mkcl_ucd_Decimal_Number,
  mkcl_ucd_Letter_Number,
  mkcl_ucd_Other_Number,
  mkcl_ucd_Connector_Punctuation,
  mkcl_ucd_Dash_Punctuation,
  mkcl_ucd_Close_Punctuation,
  mkcl_ucd_Final_Punctuation,
  mkcl_ucd_Initial_Punctuation,
  mkcl_ucd_Other_Punctuation,
  mkcl_ucd_Open_Punctuation,
  mkcl_ucd_Currency_Symbol,
  mkcl_ucd_Modifier_Symbol,
  mkcl_ucd_Math_Symbol,
  mkcl_ucd_Other_Symbol,
  mkcl_ucd_Line_Separator,
  mkcl_ucd_Paragraph_Separator,
  mkcl_ucd_Space_Separator,
};

enum mkcl_ucd_bidi_class {
  mkcl_ucd_bidi_Arabic_Letter,
  mkcl_ucd_bidi_Arabic_Number,
  mkcl_ucd_bidi_Paragraph_Separator,
  mkcl_ucd_bidi_Boundary_Neutral,
  mkcl_ucd_bidi_Common_Separator,
  mkcl_ucd_bidi_European_Number,
  mkcl_ucd_bidi_European_Separator,
  mkcl_ucd_bidi_European_Terminator,
  mkcl_ucd_bidi_Left_To_Right,
  mkcl_ucd_bidi_Left_To_Right_Embedding,
  mkcl_ucd_bidi_Left_To_Right_Override,
  mkcl_ucd_bidi_Nonspacing_Mark,
  mkcl_ucd_bidi_Other_Neutral,
  mkcl_ucd_bidi_Pop_Directional_Format,
  mkcl_ucd_bidi_Right_To_Left,
  mkcl_ucd_bidi_Right_To_Left_Embedding,
  mkcl_ucd_bidi_Right_To_Left_Override,
  mkcl_ucd_bidi_Segment_Separator,
  mkcl_ucd_bidi_White_Space,
};

struct mkcl_unichar_properties_signature
{
  enum mkcl_ucd_general_category general_category;
  enum mkcl_ucd_bidi_class bidi;
  mkcl_uint8_t canonical_combining_class;
  mkcl_uint8_t decimal_digit;
  mkcl_uint8_t digit;
  bool bidi_mirrored;
};

extern MKCL_API const struct mkcl_unichar_properties_signature
                    _mkcl_unichar_properties_signatures[];

extern MKCL_API const mkcl_uint8_t _mkcl_unichar_info_pages[];

struct mkcl_unichar_info
{
  mkcl_uint8_t properties_signature_index;
  unsigned int transform:24;
};

extern MKCL_API const struct mkcl_unichar_info _mkcl_unichar_info[][256];

#endif /* MKCL_UNICODE_H */

