# 1 "symbols_list.h"
# 1 "<built-in>"
# 1 "<command-line>"
# 1 "symbols_list.h"
# 37 "symbols_list.h"
typedef struct
{
  const char *name, *translation;
  const int narg;
} mkcl_symbol_initializer;
# 51 "symbols_list.h"
mkcl_symbol_initializer mkcl_root_symbols[] = {

  {"NIL",NULL,-1},
  {"T",NULL,-1},
  {"SI::" "UNBOUND","mk_si_unbound",0},
  {"SI::" "PROTECT-TAG",NULL,-1},


  {"&ALLOW-OTHER-KEYS",NULL,-1},
  {"&AUX",NULL,-1},
  {"&BODY",NULL,-1},
  {"&ENVIRONMENT",NULL,-1},
  {"&KEY",NULL,-1},
  {"&OPTIONAL",NULL,-1},
  {"&REST",NULL,-1},
  {"&WHOLE",NULL,-1},
  {"+","mk_cl_P",-1},
  {"++",NULL,-1},
  {"+++",NULL,-1},
  {"-","mk_cl_M",-1},
  {"*","mk_cl_X",-1},
  {"**",NULL,-1},
  {"***",NULL,-1},
  {"/","mk_cl_N",-1},
  {"//",NULL,-1},
  {"///",NULL,-1},
  {"/=","mk_cl_NE",-1},
  {"*BREAK-ON-SIGNALS*",NULL,-1},
  {"*COMPILE-FILE-PATHNAME*",NULL,-1},
  {"*COMPILE-FILE-TRUENAME*",NULL,-1},
  {"*COMPILE-PRINT*",NULL,-1},
  {"*COMPILE-VERBOSE*",NULL,-1},
  {"*DEBUG-IO*",NULL,-1},
  {"*DEBUGGER-HOOK*",NULL,-1},
  {"*DEFAULT-PATHNAME-DEFAULTS*",NULL,-1},
  {"*ERROR-OUTPUT*",NULL,-1},
  {"*FEATURES*",NULL,-1},
  {"*GENSYM-COUNTER*",NULL,-1},
  {"*LOAD-PATHNAME*",NULL,-1},
  {"*LOAD-PRINT*",NULL,-1},
  {"*LOAD-TRUENAME*",NULL,-1},
  {"*LOAD-VERBOSE*",NULL,-1},
  {"*MACROEXPAND-HOOK*",NULL,-1},
  {"*MODULES*",NULL,-1},
  {"MKCL::" "*MODULE-PROVIDER-FUNCTIONS*",NULL,-1},
  {"*PACKAGE*",NULL,-1},
  {"*PRINT-ARRAY*",NULL,-1},
  {"*PRINT-BASE*",NULL,-1},
  {"*PRINT-CASE*",NULL,-1},
  {"*PRINT-CIRCLE*",NULL,-1},
  {"*PRINT-ESCAPE*",NULL,-1},
  {"*PRINT-GENSYM*",NULL,-1},
  {"*PRINT-LENGTH*",NULL,-1},
  {"*PRINT-LEVEL*",NULL,-1},
  {"*PRINT-LINES*",NULL,-1},
  {"*PRINT-MISER-WIDTH*",NULL,-1},
  {"*PRINT-PPRINT-DISPATCH*",NULL,-1},
  {"*PRINT-PRETTY*",NULL,-1},
  {"*PRINT-RADIX*",NULL,-1},
  {"*PRINT-READABLY*",NULL,-1},
  {"*PRINT-RIGHT-MARGIN*",NULL,-1},
  {"*QUERY-IO*",NULL,-1},
  {"*RANDOM-STATE*",NULL,-1},
  {"*READ-BASE*",NULL,-1},
  {"*READ-DEFAULT-FLOAT-FORMAT*",NULL,-1},
  {"*READ-EVAL*",NULL,-1},
  {"*READ-SUPPRESS*",NULL,-1},
  {"*READTABLE*",NULL,-1},
  {"*STANDARD-INPUT*",NULL,-1},
  {"*STANDARD-OUTPUT*",NULL,-1},
  {"*TERMINAL-IO*",NULL,-1},
  {"*TRACE-OUTPUT*",NULL,-1},
  {"1+","mk_cl_1P",1},
  {"1-","mk_cl_1M",1},
  {"<","mk_cl_L",-1},
  {"<=","mk_cl_LE",-1},
  {"=","mk_cl_E",-1},
  {">","mk_cl_G",-1},
  {">=","mk_cl_GE",-1},
  {"ABORT",NULL,-1},
  {"ABS","mk_cl_abs",1},
  {"ACONS","mk_cl_acons",3},
  {"ACOS","mk_cl_acos",-1},
  {"ACOSH","mk_cl_acosh",-1},
  {"ADJOIN","mk_cl_adjoin",-1},
  {"ADJUST-ARRAY","mk_cl_adjust_array",-1},
  {"ADJUSTABLE-ARRAY-P","mk_cl_adjustable_array_p",1},
  {"ALPHA-CHAR-P","mk_cl_alpha_char_p",1},
  {"ALPHANUMERICP","mk_cl_alphanumericp",1},
  {"AND",NULL,-1},
  {"APPEND","mk_cl_append",-1},
  {"APPLY","mk_cl_apply",-1},
  {"APROPOS","mk_cl_apropos",-1},
  {"APROPOS-LIST","mk_cl_apropos_list",-1},
  {"AREF","mk_cl_aref",-1},
  {"ARITHMETIC-ERROR",NULL,-1},
  {"ARITHMETIC-ERROR-OPERANDS",NULL,-1},
  {"ARITHMETIC-ERROR-OPERATION",NULL,-1},
  {"ARRAY",NULL,-1},
  {"ARRAY-DIMENSION","mk_cl_array_dimension",2},
  {"ARRAY-DIMENSION-LIMIT",NULL,-1},
  {"ARRAY-DIMENSIONS","mk_cl_array_dimensions",1},
  {"ARRAY-DISPLACEMENT","mk_cl_array_displacement",1},
  {"ARRAY-ELEMENT-TYPE","mk_cl_array_element_type",1},
  {"ARRAY-HAS-FILL-POINTER-P","mk_cl_array_has_fill_pointer_p",1},
  {"ARRAY-IN-BOUNDS-P","mk_cl_array_in_bounds_p",-1},
  {"ARRAY-RANK","mk_cl_array_rank",1},
  {"ARRAY-RANK-LIMIT",NULL,-1},
  {"ARRAY-ROW-MAJOR-INDEX","mk_cl_array_row_major_index",-1},
  {"ARRAY-TOTAL-SIZE","mk_cl_array_total_size",1},
  {"ARRAY-TOTAL-SIZE-LIMIT",NULL,-1},
  {"ARRAYP","mk_cl_arrayp",1},
  {"ASH","mk_cl_ash",2},
  {"ASIN","mk_cl_asin",-1},
  {"ASINH","mk_cl_asinh",-1},
  {"ASSERT",NULL,-1},
  {"ASSOC","mk_cl_assoc",-1},
  {"ASSOC-IF","mk_cl_assoc_if",-1},
  {"ASSOC-IF-NOT","mk_cl_assoc_if_not",-1},
  {"ATAN","mk_cl_atan",-1},
  {"ATANH","mk_cl_atanh",-1},
  {"ATOM","mk_cl_atom",1},
  {"BASE-CHAR",NULL,-1},
  {"BASE-STRING",NULL,-1},
  {"BIGNUM",NULL,-1},
  {"BIT","mk_cl_bit",-1},
  {"BIT-AND","mk_cl_bit_and",-1},
  {"BIT-ANDC1","mk_cl_bit_andc1",-1},
  {"BIT-ANDC2","mk_cl_bit_andc2",-1},
  {"BIT-EQV","mk_cl_bit_eqv",-1},
  {"BIT-IOR","mk_cl_bit_ior",-1},
  {"BIT-NAND","mk_cl_bit_nand",-1},
  {"BIT-NOR","mk_cl_bit_nor",-1},
  {"BIT-NOT","mk_cl_bit_not",-1},
  {"BIT-ORC1","mk_cl_bit_orc1",-1},
  {"BIT-ORC2","mk_cl_bit_orc2",-1},
  {"BIT-VECTOR",NULL,-1},
  {"BIT-VECTOR-P","mk_cl_bit_vector_p",1},
  {"BIT-XOR","mk_cl_bit_xor",-1},
  {"BLOCK",NULL,-1},
  {"BOOLE","mk_cl_boole",3},
  {"BOOLE-1",NULL,-1},
  {"BOOLE-2",NULL,-1},
  {"BOOLE-AND",NULL,-1},
  {"BOOLE-ANDC1",NULL,-1},
  {"BOOLE-ANDC2",NULL,-1},
  {"BOOLE-C1",NULL,-1},
  {"BOOLE-C2",NULL,-1},
  {"BOOLE-CLR",NULL,-1},
  {"BOOLE-EQV",NULL,-1},
  {"BOOLE-IOR",NULL,-1},
  {"BOOLE-NAND",NULL,-1},
  {"BOOLE-NOR",NULL,-1},
  {"BOOLE-ORC1",NULL,-1},
  {"BOOLE-ORC2",NULL,-1},
  {"BOOLE-SET",NULL,-1},
  {"BOOLE-XOR",NULL,-1},
  {"BOOLEAN",NULL,-1},
  {"BOTH-CASE-P","mk_cl_both_case_p",1},
  {"BOUNDP","mk_cl_boundp",1},
  {"BREAK",NULL,-1},
  {"BROADCAST-STREAM",NULL,-1},
  {"BROADCAST-STREAM-STREAMS","mk_cl_broadcast_stream_streams",1},
  {"BUTLAST","mk_cl_butlast",-1},
  {"BYTE","mk_cl_byte",-1},
  {"BYTE-POSITION","mk_cl_byte_position",-1},
  {"BYTE-SIZE","mk_cl_byte_size",-1},
  {"CAAAAR","mk_cl_caaaar",1},
  {"CAAADR","mk_cl_caaadr",1},
  {"CAAAR","mk_cl_caaar",1},
  {"CAADAR","mk_cl_caadar",1},
  {"CAADDR","mk_cl_caaddr",1},
  {"CAADR","mk_cl_caadr",1},
  {"CAAR","mk_cl_caar",1},
  {"CADAAR","mk_cl_cadaar",1},
  {"CADADR","mk_cl_cadadr",1},
  {"CADAR","mk_cl_cadar",1},
  {"CADDAR","mk_cl_caddar",1},
  {"CADDDR","mk_cl_cadddr",1},
  {"CADDR","mk_cl_caddr",1},
  {"CADR","mk_cl_cadr",1},
  {"CALL-ARGUMENTS-LIMIT",NULL,-1},
  {"CAR","mk_cl_car",1},
  {"CASE",NULL,-1},
  {"CATCH",NULL,-1},
  {"CCASE",NULL,-1},
  {"CDAAAR","mk_cl_cdaaar",1},
  {"CDAADR","mk_cl_cdaadr",1},
  {"CDAAR","mk_cl_cdaar",1},
  {"CDADAR","mk_cl_cdadar",1},
  {"CDADDR","mk_cl_cdaddr",1},
  {"CDADR","mk_cl_cdadr",1},
  {"CDAR","mk_cl_cdar",1},
  {"CDDAAR","mk_cl_cddaar",1},
  {"CDDADR","mk_cl_cddadr",1},
  {"CDDAR","mk_cl_cddar",1},
  {"CDDDAR","mk_cl_cdddar",1},
  {"CDDDDR","mk_cl_cddddr",1},
  {"CDDDR","mk_cl_cdddr",1},
  {"CDDR","mk_cl_cddr",1},
  {"CDR","mk_cl_cdr",1},
  {"CEILING","mk_cl_ceiling",-1},
  {"CELL-ERROR",NULL,-1},
  {"CELL-ERROR-NAME",NULL,-1},
  {"CERROR","mk_cl_cerror",-1},
  {"CHAR","mk_cl_char",2},
  {"CHAR-CODE","mk_cl_char_code",1},
  {"CHAR-CODE-LIMIT",NULL,-1},
  {"CHAR-DOWNCASE","mk_cl_char_downcase",1},
  {"CHAR-EQUAL","mk_cl_char_equal",-1},
  {"CHAR-GREATERP","mk_cl_char_greaterp",-1},
  {"CHAR-INT","mk_cl_char_int",1},
  {"CHAR-LESSP","mk_cl_char_lessp",-1},
  {"CHAR-NAME","mk_cl_char_name",1},
  {"CHAR-NOT-EQUAL","mk_cl_char_not_equal",-1},
  {"CHAR-NOT-GREATERP","mk_cl_char_not_greaterp",-1},
  {"CHAR-NOT-LESSP","mk_cl_char_not_lessp",-1},
  {"CHAR-UPCASE","mk_cl_char_upcase",1},
  {"CHAR/=","mk_cl_charNE",-1},
  {"CHAR<","mk_cl_charL",-1},
  {"CHAR<=","mk_cl_charLE",-1},
  {"CHAR=","mk_cl_charE",-1},
  {"CHAR>","mk_cl_charG",-1},
  {"CHAR>=","mk_cl_charGE",-1},
  {"CHARACTER","mk_cl_character",1},
  {"CHARACTERP","mk_cl_characterp",1},
  {"CHECK-TYPE",NULL,-1},
  {"CIS","mk_cl_cis",-1},
  {"CLEAR-INPUT","mk_cl_clear_input",-1},
  {"CLEAR-OUTPUT","mk_cl_clear_output",-1},
  {"CLOSE","mk_cl_close",-1},
  {"CLRHASH","mk_cl_clrhash",1},
  {"CODE-CHAR","mk_cl_code_char",1},
  {"COERCE","mk_cl_coerce",-1},
  {"COMPILATION-SPEED",NULL,-1},
  {"COMPILE",NULL,-1},
  {"COMPILE-FILE",NULL,-1},
  {"COMPILE-FILE-PATHNAME",NULL,-1},
  {"COMPILED-FUNCTION",NULL,-1},
  {"COMPILED-FUNCTION-P","mk_cl_compiled_function_p",1},
  {"COMPILER-MACRO",NULL,-1},
  {"COMPILER-MACRO-FUNCTION",NULL,-1},
  {"COMPLEMENT",NULL,-1},
  {"COMPLEX","mk_cl_complex",-1},
  {"COMPLEXP","mk_cl_complexp",1},
  {"COMPUTE-RESTARTS",NULL,-1},
  {"CONCATENATE","mk_cl_concatenate",-1},
  {"CONCATENATED-STREAM",NULL,-1},
  {"CONCATENATED-STREAM-STREAMS","mk_cl_concatenated_stream_streams",1},
  {"COND",NULL,-1},
  {"CONDITION",NULL,-1},
  {"CONJUGATE","mk_cl_conjugate",1},
  {"CONTINUE","mk_cl_continue",-1},
  {"CONS","mk_cl_cons",2},
  {"CONSP","mk_cl_consp",1},
  {"CONSTANTLY","mk_cl_constantly",-1},
  {"CONSTANTP","mk_cl_constantp",-1},
  {"CONTROL-ERROR",NULL,-1},
  {"COPY-ALIST","mk_cl_copy_alist",1},
  {"COPY-LIST","mk_cl_copy_list",1},
  {"COPY-PPRINT-DISPATCH","mk_cl_copy_pprint_dispatch",-1},
  {"COPY-READTABLE","mk_cl_copy_readtable",-1},
  {"COPY-SEQ","mk_cl_copy_seq",1},
  {"COPY-STRUCTURE","mk_cl_copy_structure",1},
  {"COPY-SYMBOL","mk_cl_copy_symbol",-1},
  {"COPY-TREE","mk_cl_copy_tree",1},
  {"COS","mk_cl_cos",1},
  {"COSH","mk_cl_cosh",1},
  {"COUNT","mk_cl_count",-1},
  {"COUNT-IF","mk_cl_count_if",-1},
  {"COUNT-IF-NOT","mk_cl_count_if_not",-1},
  {"CTYPECASE",NULL,-1},
  {"DEBUG",NULL,-1},
  {"DECF",NULL,-1},
  {"DECLAIM",NULL,-1},
  {"DECLARATION",NULL,-1},
  {"DECLARE",NULL,-1},
  {"DECODE-FLOAT","mk_cl_decode_float",1},
  {"DECODE-UNIVERSAL-TIME","mk_cl_decode_universal_time",-1},
  {"DEFCONSTANT",NULL,-1},
  {"DEFINE-CONDITION",NULL,-1},
  {"DEFINE-COMPILER-MACRO",NULL,-1},
  {"DEFINE-MODIFY-MACRO",NULL,-1},
  {"DEFINE-SETF-EXPANDER",NULL,-1},
  {"DEFINE-SYMBOL-MACRO",NULL,-1},
  {"DEFMACRO",NULL,-1},
  {"DEFPACKAGE",NULL,-1},
  {"DEFPARAMETER",NULL,-1},
  {"DEFSETF",NULL,-1},
  {"DEFSTRUCT",NULL,-1},
  {"DEFTYPE",NULL,-1},
  {"DEFUN",NULL,-1},
  {"DEFVAR",NULL,-1},
  {"DELETE","mk_cl_delete",-1},
  {"DELETE-DUPLICATES","mk_cl_delete_duplicates",-1},
  {"DELETE-FILE","mk_cl_delete_file",1},
  {"DELETE-IF","mk_cl_delete_if",-1},
  {"DELETE-IF-NOT","mk_cl_delete_if_not",-1},
  {"DELETE-PACKAGE","mk_cl_delete_package",1},
  {"DENOMINATOR","mk_cl_denominator",1},
  {"DEPOSIT-FIELD","mk_cl_deposit_field",-1},
  {"DESCRIBE",NULL,-1},
  {"DESTRUCTURING-BIND",NULL,-1},
  {"DIGIT-CHAR","mk_cl_digit_char",-1},
  {"DIGIT-CHAR-P","mk_cl_digit_char_p",-1},
  {"DIRECTORY","mk_cl_directory",-1},
  {"DIRECTORY-NAMESTRING","mk_cl_directory_namestring",1},
  {"DISASSEMBLE",NULL,-1},
  {"DIVISION-BY-ZERO",NULL,-1},
  {"DO",NULL,-1},
  {"DO*",NULL,-1},
  {"DO-ALL-SYMBOLS",NULL,-1},
  {"DO-EXTERNAL-SYMBOLS",NULL,-1},
  {"DO-SYMBOLS",NULL,-1},
  {"DOCUMENTATION",NULL,-1},
  {"DOLIST",NULL,-1},
  {"DOTIMES",NULL,-1},
  {"DOUBLE-FLOAT",NULL,-1},
  {"DOUBLE-FLOAT-EPSILON",NULL,-1},
  {"DOUBLE-FLOAT-NEGATIVE-EPSILON",NULL,-1},
  {"DPB","mk_cl_dpb",-1},
  {"DRIBBLE",NULL,-1},
  {"DYNAMIC-EXTENT",NULL,-1},
  {"ECASE",NULL,-1},
  {"ECHO-STREAM",NULL,-1},
  {"ECHO-STREAM-INPUT-STREAM","mk_cl_echo_stream_input_stream",1},
  {"ECHO-STREAM-OUTPUT-STREAM","mk_cl_echo_stream_output_stream",1},
  {"ED",NULL,-1},
  {"EIGHTH","mk_cl_eighth",1},
  {"ELT","mk_cl_elt",2},
  {"ENCODE-UNIVERSAL-TIME","mk_cl_encode_universal_time",-1},
  {"END-OF-FILE",NULL,-1},
  {"ENDP","mk_cl_endp",1},
  {"ENOUGH-NAMESTRING","mk_cl_enough_namestring",-1},
  {"ENSURE-DIRECTORIES-EXIST","mk_cl_ensure_directories_exist",-1},
  {"EQ","mk_cl_eq",2},
  {"EQL","mk_cl_eql",2},
  {"EQUAL","mk_cl_equal",2},
  {"EQUALP","mk_cl_equalp",2},
  {"ERROR","mk_cl_error",-1},
  {"ETYPECASE",NULL,-1},
  {"EVAL","mk_cl_eval",1},
  {"EVAL-WHEN",NULL,-1},
  {"EVENP","mk_cl_evenp",1},
  {"EVERY","mk_cl_every",-1},
  {"EXP","mk_cl_exp",1},
  {"EXPORT","mk_cl_export",-1},
  {"EXPT","mk_cl_expt",2},
  {"EXTENDED-CHAR",NULL,-1},
  {"FBOUNDP","mk_cl_fboundp",1},
  {"FCEILING","mk_cl_fceiling",-1},
  {"FDEFINITION","mk_cl_fdefinition",1},
  {"FFLOOR","mk_cl_ffloor",-1},
  {"FIFTH","mk_cl_fifth",1},
  {"FILE-AUTHOR","mk_cl_file_author",1},
  {"FILE-ERROR",NULL,-1},
  {"FILE-ERROR-PATHNAME",NULL,-1},
  {"FILE-LENGTH","mk_cl_file_length",1},
  {"FILE-NAMESTRING","mk_cl_file_namestring",1},
  {"FILE-POSITION","mk_cl_file_position",-1},
  {"FILE-STREAM",NULL,-1},
  {"FILE-STRING-LENGTH","mk_cl_file_string_length",2},
  {"FILE-WRITE-DATE","mk_cl_file_write_date",1},
  {"FILL","mk_cl_fill",-1},
  {"FILL-POINTER","mk_cl_fill_pointer",1},
  {"FIND","mk_cl_find",-1},
  {"FIND-ALL-SYMBOLS","mk_cl_find_all_symbols",-1},
  {"FIND-IF","mk_cl_find_if",-1},
  {"FIND-IF-NOT","mk_cl_find_if_not",-1},
  {"FIND-PACKAGE","mk_cl_find_package",1},
  {"FIND-RESTART",NULL,-1},
  {"FIND-SYMBOL","mk_cl_find_symbol",-1},
  {"FINISH-OUTPUT","mk_cl_finish_output",-1},
  {"FIRST","mk_cl_car",1},
  {"FIXNUM",NULL,-1},
  {"FLET",NULL,-1},
  {"FLOAT","mk_cl_float",-1},
  {"FLOAT-DIGITS","mk_cl_float_digits",1},
  {"FLOAT-PRECISION","mk_cl_float_precision",1},
  {"FLOAT-RADIX","mk_cl_float_radix",1},
  {"FLOAT-SIGN","mk_cl_float_sign",-1},
  {"FLOATING-POINT-INEXACT",NULL,-1},
  {"FLOATING-POINT-INVALID-OPERATION",NULL,-1},
  {"FLOATING-POINT-OVERFLOW",NULL,-1},
  {"FLOATING-POINT-UNDERFLOW",NULL,-1},
  {"FLOATP","mk_cl_floatp",1},
  {"FLOOR","mk_cl_floor",-1},
  {"FMAKUNBOUND","mk_cl_fmakunbound",1},
  {"FORCE-OUTPUT","mk_cl_force_output",-1},
  {"FORMAT","mk_cl_format",-1},
  {"FORMATTER",NULL,-1},
  {"FOURTH","mk_cl_cadddr",1},
  {"FRESH-LINE","mk_cl_fresh_line",-1},
  {"FROUND","mk_cl_fround",-1},
  {"FTRUNCATE","mk_cl_ftruncate",-1},
  {"FTYPE",NULL,-1},
  {"FUNCALL","mk_cl_funcall",-1},
  {"FUNCTION-LAMBDA-EXPRESSION","mk_cl_function_lambda_expression",1},
  {"FUNCTION",NULL,-1},
  {"FUNCTION-KEYWORDS",NULL,-1},
  {"FUNCTIONP","mk_cl_functionp",1},
  {"GCD","mk_cl_gcd",-1},
  {"GENSYM","mk_cl_gensym",-1},
  {"GENTEMP","mk_cl_gentemp",-1},
  {"GET","mk_cl_get",-1},
  {"GET-DECODED-TIME","mk_cl_get_decoded_time",-1},
  {"GET-DISPATCH-MACRO-CHARACTER","mk_cl_get_dispatch_macro_character",-1},
  {"GET-INTERNAL-REAL-TIME","mk_cl_get_internal_real_time",0},
  {"GET-INTERNAL-RUN-TIME","mk_cl_get_internal_run_time",0},
  {"GET-MACRO-CHARACTER","mk_cl_get_macro_character",-1},
  {"GET-OUTPUT-STREAM-STRING","mk_cl_get_output_stream_string",1},
  {"GET-PROPERTIES","mk_cl_get_properties",2},
  {"GET-SETF-EXPANSION",NULL,-1},
  {"GET-UNIVERSAL-TIME","mk_cl_get_universal_time",0},
  {"GETF","mk_cl_getf",-1},
  {"GETHASH","mk_cl_gethash",-1},
  {"GO",NULL,-1},
  {"GRAPHIC-CHAR-P","mk_cl_graphic_char_p",1},
  {"HANDLER-CASE",NULL,-1},
  {"HANDLER-BIND",NULL,-1},
  {"HASH-TABLE",NULL,-1},
  {"HASH-TABLE-COUNT","mk_cl_hash_table_count",1},
  {"HASH-TABLE-P","mk_cl_hash_table_p",1},
  {"HASH-TABLE-REHASH-SIZE","mk_cl_hash_table_rehash_size",1},
  {"HASH-TABLE-REHASH-THRESHOLD","mk_cl_hash_table_rehash_threshold",1},
  {"HASH-TABLE-SIZE","mk_cl_hash_table_size",1},
  {"HASH-TABLE-TEST","mk_cl_hash_table_test",1},
  {"HOST-NAMESTRING","mk_cl_host_namestring",1},
  {"IDENTITY","mk_cl_identity",1},
  {"IGNORABLE",NULL,-1},
  {"IGNORE",NULL,-1},
  {"IGNORE-ERRORS",NULL,-1},
  {"IMAGPART","mk_cl_imagpart",1},
  {"IMPORT","mk_cl_import",-1},
  {"IN-PACKAGE",NULL,-1},
  {"INCF",NULL,-1},
  {"INLINE",NULL,-1},
  {"INPUT-STREAM-P","mk_cl_input_stream_p",1},
  {"INSPECT",NULL,-1},
  {"INTEGER",NULL,-1},
  {"INTEGER-DECODE-FLOAT","mk_cl_integer_decode_float",1},
  {"INTEGER-LENGTH","mk_cl_integer_length",1},
  {"INTEGERP","mk_cl_integerp",1},
  {"INTERACTIVE-STREAM-P","mk_cl_interactive_stream_p",1},
  {"INTERN","mk_cl_intern",-1},
  {"INTERNAL-TIME-UNITS-PER-SECOND",NULL,-1},
  {"INTERSECTION","mk_cl_intersection",-1},
  {"INVOKE-DEBUGGER",NULL,-1},
  {"INVOKE-RESTART",NULL,-1},
  {"INVOKE-RESTART-INTERACTIVELY",NULL,-1},
  {"ISQRT","mk_cl_isqrt",-1},
  {"KEYWORD",NULL,-1},
  {"KEYWORDP","mk_cl_keywordp",1},
  {"LABELS",NULL,-1},
  {"LAMBDA",NULL,-1},
  {"LAMBDA-LIST-KEYWORDS",NULL,-1},
  {"LAMBDA-PARAMETERS-LIMIT",NULL,-1},
  {"LAST","mk_cl_last",-1},
  {"LCM","mk_cl_lcm",-1},
  {"LDB","mk_cl_ldb",-1},
  {"LDB-TEST","mk_cl_ldb_test",-1},
  {"LDIFF","mk_cl_ldiff",2},
  {"LEAST-NEGATIVE-DOUBLE-FLOAT",NULL,-1},
  {"LEAST-NEGATIVE-LONG-FLOAT",NULL,-1},
  {"LEAST-NEGATIVE-NORMALIZED-DOUBLE-FLOAT",NULL,-1},
  {"LEAST-NEGATIVE-NORMALIZED-LONG-FLOAT",NULL,-1},
  {"LEAST-NEGATIVE-NORMALIZED-SHORT-FLOAT",NULL,-1},
  {"LEAST-NEGATIVE-NORMALIZED-SINGLE-FLOAT",NULL,-1},
  {"LEAST-NEGATIVE-SHORT-FLOAT",NULL,-1},
  {"LEAST-NEGATIVE-SINGLE-FLOAT",NULL,-1},
  {"LEAST-POSITIVE-DOUBLE-FLOAT",NULL,-1},
  {"LEAST-POSITIVE-LONG-FLOAT",NULL,-1},
  {"LEAST-POSITIVE-NORMALIZED-DOUBLE-FLOAT",NULL,-1},
  {"LEAST-POSITIVE-NORMALIZED-LONG-FLOAT",NULL,-1},
  {"LEAST-POSITIVE-NORMALIZED-SHORT-FLOAT",NULL,-1},
  {"LEAST-POSITIVE-NORMALIZED-SINGLE-FLOAT",NULL,-1},
  {"LEAST-POSITIVE-SHORT-FLOAT",NULL,-1},
  {"LEAST-POSITIVE-SINGLE-FLOAT",NULL,-1},
  {"LENGTH","mk_cl_length",1},
  {"LET",NULL,-1},
  {"LET*",NULL,-1},
  {"LISP-IMPLEMENTATION-TYPE",NULL,-1},
  {"LISP-IMPLEMENTATION-VERSION",NULL,-1},
  {"LIST","mk_cl_list",-1},
  {"LIST*","mk_cl_listX",-1},
  {"LIST-ALL-PACKAGES","mk_cl_list_all_packages",0},
  {"LIST-LENGTH","mk_cl_list_length",1},
  {"LISTEN","mk_cl_listen",-1},
  {"LISTP","mk_cl_listp",1},
  {"LOAD","mk_cl_load",-1},
  {"LOAD-LOGICAL-PATHNAME-TRANSLATIONS","mk_cl_load_logical_pathname_translations",-1},
  {"LOAD-TIME-VALUE",NULL,-1},
  {"LOCALLY",NULL,-1},
  {"LOG","mk_cl_log",-1},
  {"LOGAND","mk_cl_logand",-1},
  {"LOGANDC1","mk_cl_logandc1",2},
  {"LOGANDC2","mk_cl_logandc2",2},
  {"LOGBITP","mk_cl_logbitp",2},
  {"LOGCOUNT","mk_cl_logcount",1},
  {"LOGEQV","mk_cl_logeqv",-1},
  {"LOGICAL-PATHNAME","mk_cl_logical_pathname",1},
  {"LOGICAL-PATHNAME-TRANSLATIONS","mk_cl_logical_pathname_translations",-1},
  {"LOGIOR","mk_cl_logior",-1},
  {"LOGNAND","mk_cl_lognand",2},
  {"LOGNOR","mk_cl_lognor",2},
  {"LOGNOT","mk_cl_lognot",1},
  {"LOGORC1","mk_cl_logorc1",2},
  {"LOGORC2","mk_cl_logorc2",2},
  {"LOGTEST","mk_cl_logtest",-1},
  {"LOGXOR","mk_cl_logxor",-1},
  {"LONG-FLOAT",NULL,-1},
  {"LONG-FLOAT-EPSILON",NULL,-1},
  {"LONG-FLOAT-NEGATIVE-EPSILON",NULL,-1},
  {"LONG-SITE-NAME",NULL,-1},
  {"LOOP",NULL,-1},
  {"LOOP-FINISH",NULL,-1},
  {"LOWER-CASE-P","mk_cl_lower_case_p",1},
  {"MACHINE-INSTANCE",NULL,-1},
  {"MACHINE-TYPE",NULL,-1},
  {"MACHINE-VERSION",NULL,-1},
  {"MACRO-FUNCTION","mk_cl_macro_function",-1},
  {"MACROEXPAND","mk_cl_macroexpand",-1},
  {"MACROEXPAND-1","mk_cl_macroexpand_1",-1},
  {"MACROLET",NULL,-1},
  {"MAKE-ARRAY","mk_cl_make_array",-1},
  {"MAKE-BROADCAST-STREAM","mk_cl_make_broadcast_stream",-1},
  {"MAKE-CONDITION",NULL,-1},
  {"MAKE-CONCATENATED-STREAM","mk_cl_make_concatenated_stream",-1},
  {"MAKE-DISPATCH-MACRO-CHARACTER","mk_cl_make_dispatch_macro_character",-1},
  {"MAKE-ECHO-STREAM","mk_cl_make_echo_stream",2},
  {"MAKE-HASH-TABLE","mk_cl_make_hash_table",-1},
  {"MAKE-LIST","mk_cl_make_list",-1},
  {"MAKE-PACKAGE","mk_cl_make_package",-1},
  {"MAKE-PATHNAME","mk_cl_make_pathname",-1},
  {"MAKE-RANDOM-STATE","mk_cl_make_random_state",-1},
  {"MAKE-SEQUENCE","mk_cl_make_sequence",-1},
  {"MAKE-STRING","mk_cl_make_string",-1},
  {"MAKE-STRING-INPUT-STREAM","mk_cl_make_string_input_stream",-1},
  {"MAKE-STRING-OUTPUT-STREAM","mk_cl_make_string_output_stream",-1},
  {"MAKE-SYMBOL","mk_cl_make_symbol",1},
  {"MAKE-SYNONYM-STREAM","mk_cl_make_synonym_stream",1},
  {"MAKE-TWO-WAY-STREAM","mk_cl_make_two_way_stream",2},
  {"MAKUNBOUND","mk_cl_makunbound",1},
  {"MAP","mk_cl_map",-1},
  {"MAP-INTO","mk_cl_map_into",-1},
  {"MAPC","mk_cl_mapc",-1},
  {"MAPCAN","mk_cl_mapcan",-1},
  {"MAPCAR","mk_cl_mapcar",-1},
  {"MAPCON","mk_cl_mapcon",-1},
  {"MAPHASH","mk_cl_maphash",2},
  {"MAPL","mk_cl_mapl",-1},
  {"MAPLIST","mk_cl_maplist",-1},
  {"MASK-FIELD","mk_cl_mask_field",-1},
  {"MAX","mk_cl_max",-1},
  {"MEMBER","mk_cl_member",-1},
  {"MEMBER-IF","mk_cl_member_if",-1},
  {"MEMBER-IF-NOT","mk_cl_member_if_not",-1},
  {"MERGE","mk_cl_merge",-1},
  {"MERGE-PATHNAMES","mk_cl_merge_pathnames",-1},
  {"MIN","mk_cl_min",-1},
  {"MINUSP","mk_cl_minusp",1},
  {"MISMATCH","mk_cl_mismatch",-1},
  {"MOD","mk_cl_mod",2},
  {"MOST-NEGATIVE-DOUBLE-FLOAT",NULL,-1},
  {"MOST-NEGATIVE-FIXNUM",NULL,-1},
  {"MOST-NEGATIVE-LONG-FLOAT",NULL,-1},
  {"MOST-NEGATIVE-SHORT-FLOAT",NULL,-1},
  {"MOST-NEGATIVE-SINGLE-FLOAT",NULL,-1},
  {"MOST-POSITIVE-DOUBLE-FLOAT",NULL,-1},
  {"MOST-POSITIVE-FIXNUM",NULL,-1},
  {"MOST-POSITIVE-LONG-FLOAT",NULL,-1},
  {"MOST-POSITIVE-SHORT-FLOAT",NULL,-1},
  {"MOST-POSITIVE-SINGLE-FLOAT",NULL,-1},
  {"MUFFLE-WARNING",NULL,-1},
  {"MULTIPLE-VALUE-BIND",NULL,-1},
  {"MULTIPLE-VALUE-CALL",NULL,-1},
  {"MULTIPLE-VALUE-LIST",NULL,-1},
  {"MULTIPLE-VALUE-PROG1",NULL,-1},
  {"MULTIPLE-VALUE-SETQ",NULL,-1},
  {"MULTIPLE-VALUES-LIMIT",NULL,-1},
  {"NAME-CHAR","mk_cl_name_char",1},
  {"NAMESTRING","mk_cl_namestring",1},
  {"NBUTLAST","mk_cl_nbutlast",-1},
  {"NCONC","mk_cl_nconc",-1},
  {"NINTERSECTION","mk_cl_nintersection",-1},
  {"NINTH","mk_cl_ninth",1},
  {"NOT","mk_cl_not",1},
  {"NOTANY","mk_cl_notany",-1},
  {"NOTEVERY","mk_cl_notevery",-1},
  {"NOTINLINE",NULL,-1},
  {"NRECONC","mk_cl_nreconc",2},
  {"NREVERSE","mk_cl_nreverse",1},
  {"NSET-DIFFERENCE","mk_cl_nset_difference",-1},
  {"NSET-EXCLUSIVE-OR","mk_cl_nset_exclusive_or",-1},
  {"NSTRING-CAPITALIZE","mk_cl_nstring_capitalize",-1},
  {"NSTRING-DOWNCASE","mk_cl_nstring_downcase",-1},
  {"NSTRING-UPCASE","mk_cl_nstring_upcase",-1},
  {"NSUBLIS","mk_cl_nsublis",-1},
  {"NSUBST","mk_cl_nsubst",-1},
  {"NSUBST-IF","mk_cl_nsubst_if",-1},
  {"NSUBST-IF-NOT","mk_cl_nsubst_if_not",-1},
  {"NSUBSTITUTE","mk_cl_nsubstitute",-1},
  {"NSUBSTITUTE-IF","mk_cl_nsubstitute_if",-1},
  {"NSUBSTITUTE-IF-NOT","mk_cl_nsubstitute_if_not",-1},
  {"NTH","mk_cl_nth",2},
  {"NTH-VALUE",NULL,-1},
  {"NTHCDR","mk_cl_nthcdr",2},
  {"NULL","mk_cl_null",1},
  {"NUMBER",NULL,-1},
  {"NUMBERP","mk_cl_numberp",1},
  {"NUMERATOR","mk_cl_numerator",1},
  {"NUNION","mk_cl_nunion",-1},
  {"ODDP","mk_cl_oddp",1},
  {"OPEN","mk_cl_open",-1},
  {"OPEN-STREAM-P","mk_cl_open_stream_p",1},
  {"OPTIMIZE",NULL,-1},
  {"OR",NULL,-1},
  {"OTHERWISE",NULL,-1},
  {"OUTPUT-STREAM-P","mk_cl_output_stream_p",1},
  {"PACKAGE",NULL,-1},
  {"PACKAGE-ERROR",NULL,-1},
  {"PACKAGE-ERROR-PACKAGE",NULL,-1},
  {"PACKAGE-NAME","mk_cl_package_name",1},
  {"PACKAGE-NICKNAMES","mk_cl_package_nicknames",1},
  {"PACKAGE-SHADOWING-SYMBOLS","mk_cl_package_shadowing_symbols",1},
  {"PACKAGE-USE-LIST","mk_cl_package_use_list",1},
  {"PACKAGE-USED-BY-LIST","mk_cl_package_used_by_list",1},
  {"PACKAGEP","mk_cl_packagep",1},
  {"PAIRLIS","mk_cl_pairlis",-1},
  {"PARSE-ERROR",NULL,-1},
  {"PARSE-INTEGER","mk_cl_parse_integer",-1},
  {"PARSE-NAMESTRING","mk_cl_parse_namestring",-1},
  {"PATHNAME","mk_cl_pathname",1},
  {"PATHNAME-DEVICE","mk_cl_pathname_device",-1},
  {"PATHNAME-DIRECTORY","mk_cl_pathname_directory",-1},
  {"PATHNAME-HOST","mk_cl_pathname_host",-1},
  {"PATHNAME-MATCH-P","mk_cl_pathname_match_p",2},
  {"PATHNAME-NAME","mk_cl_pathname_name",-1},
  {"PATHNAME-TYPE","mk_cl_pathname_type",-1},
  {"PATHNAME-VERSION","mk_cl_pathname_version",1},
  {"PATHNAMEP","mk_cl_pathnamep",1},
  {"PEEK-CHAR","mk_cl_peek_char",-1},
  {"PHASE","mk_cl_phase",-1},
  {"PI",NULL,-1},
  {"PLUSP","mk_cl_plusp",1},
  {"POP",NULL,-1},
  {"POSITION","mk_cl_position",-1},
  {"POSITION-IF","mk_cl_position_if",-1},
  {"POSITION-IF-NOT","mk_cl_position_if_not",-1},
  {"PPRINT","mk_cl_pprint",-1},
  {"PPRINT-DISPATCH","mk_cl_pprint_dispatch",-1},
  {"PPRINT-EXIT-IF-LIST-EXHAUSTED",NULL,-1},
  {"PPRINT-FILL","mk_cl_pprint_fill",-1},
  {"PPRINT-INDENT","mk_cl_pprint_indent",-1},
  {"PPRINT-LINEAR","mk_cl_pprint_linear",-1},
  {"PPRINT-LOGICAL-BLOCK",NULL,-1},
  {"PPRINT-NEWLINE","mk_cl_pprint_newline",-1},
  {"PPRINT-POP",NULL,-1},
  {"PPRINT-TAB","mk_cl_pprint_tab",-1},
  {"PPRINT-TABULAR","mk_cl_pprint_tabular",-1},
  {"PRIN1","mk_cl_prin1",-1},
  {"PRIN1-TO-STRING","mk_cl_prin1_to_string",-1},
  {"PRINC","mk_cl_princ",-1},
  {"PRINC-TO-STRING","mk_cl_princ_to_string",-1},
  {"PRINT","mk_cl_print",-1},
  {"PRINT-NOT-READABLE",NULL,-1},
  {"PRINT-NOT-READABLE-OBJECT",NULL,-1},
  {"PROBE-FILE","mk_cl_probe_file",1},
  {"PROCLAIM",NULL,-1},
  {"PROG",NULL,-1},
  {"PROG*",NULL,-1},
  {"PROG1",NULL,-1},
  {"PROG2",NULL,-1},
  {"PROGN",NULL,-1},
  {"PROGRAM-ERROR",NULL,-1},
  {"PROGV",NULL,-1},
  {"PROVIDE","mk_cl_provide",-1},
  {"PSETF",NULL,-1},
  {"PSETQ",NULL,-1},
  {"PUSH",NULL,-1},
  {"PUSHNEW",NULL,-1},
  {"QUOTE",NULL,-1},
  {"RANDOM","mk_cl_random",-1},
  {"RANDOM-STATE",NULL,-1},
  {"RANDOM-STATE-P","mk_cl_random_state_p",1},
  {"RASSOC","mk_cl_rassoc",-1},
  {"RASSOC-IF","mk_cl_rassoc_if",-1},
  {"RASSOC-IF-NOT","mk_cl_rassoc_if_not",-1},
  {"RATIO",NULL,-1},
  {"RATIONAL","mk_cl_rational",1},
  {"RATIONALIZE","mk_cl_rationalize",1},
  {"RATIONALP","mk_cl_rationalp",1},
  {"READ","mk_cl_read",-1},
  {"READ-BYTE","mk_cl_read_byte",-1},
  {"READ-CHAR","mk_cl_read_char",-1},
  {"READ-CHAR-NO-HANG","mk_cl_read_char_no_hang",-1},
  {"READ-DELIMITED-LIST","mk_cl_read_delimited_list",-1},
  {"READ-FROM-STRING","mk_cl_read_from_string",-1},
  {"READ-LINE","mk_cl_read_line",-1},
  {"READ-PRESERVING-WHITESPACE","mk_cl_read_preserving_whitespace",-1},
  {"READ-SEQUENCE","mk_cl_read_sequence",-1},
  {"READER-ERROR",NULL,-1},
  {"READTABLE",NULL,-1},
  {"READTABLE-CASE","mk_cl_readtable_case",1},
  {"READTABLEP","mk_cl_readtablep",1},
  {"REAL",NULL,-1},
  {"REALP","mk_cl_realp",1},
  {"REALPART","mk_cl_realpart",1},
  {"REDUCE","mk_cl_reduce",-1},
  {"REM","mk_cl_rem",2},
  {"REMF",NULL,-1},
  {"REMHASH","mk_cl_remhash",2},
  {"REMOVE","mk_cl_remove",-1},
  {"REMOVE-DUPLICATES","mk_cl_remove_duplicates",-1},
  {"REMOVE-IF","mk_cl_remove_if",-1},
  {"REMOVE-IF-NOT","mk_cl_remove_if_not",-1},
  {"REMPROP","mk_cl_remprop",2},
  {"RENAME-FILE","mk_cl_rename_file",2},
  {"RENAME-PACKAGE","mk_cl_rename_package",-1},
  {"REPLACE","mk_cl_replace",-1},
  {"REQUIRE","mk_cl_require",-1},
  {"REST","mk_cl_cdr",1},
  {"RESTART",NULL,-1},
  {"RESTART-BIND",NULL,-1},
  {"RESTART-CASE",NULL,-1},
  {"RESTART-NAME",NULL,-1},
  {"RETURN",NULL,-1},
  {"RETURN-FROM",NULL,-1},
  {"REVAPPEND","mk_cl_revappend",2},
  {"REVERSE","mk_cl_reverse",1},
  {"ROOM",NULL,-1},
  {"ROTATEF",NULL,-1},
  {"ROUND","mk_cl_round",-1},
  {"ROW-MAJOR-AREF","mk_cl_row_major_aref",2},
  {"RPLACA","mk_cl_rplaca",2},
  {"RPLACD","mk_cl_rplacd",2},
  {"SAFETY",NULL,-1},
  {"SATISFIES",NULL,-1},
  {"SBIT","mk_cl_sbit",-1},
  {"SCALE-FLOAT","mk_cl_scale_float",2},
  {"SCHAR","mk_cl_char",2},
  {"SEARCH","mk_cl_search",-1},
  {"SECOND","mk_cl_cadr",1},
  {"SEQUENCE",NULL,-1},
  {"SERIOUS-CONDITION",NULL,-1},
  {"SET","mk_cl_set",2},
  {"SET-DIFFERENCE","mk_cl_set_difference",-1},
  {"SET-DISPATCH-MACRO-CHARACTER","mk_cl_set_dispatch_macro_character",-1},
  {"SET-EXCLUSIVE-OR","mk_cl_set_exclusive_or",-1},
  {"SET-MACRO-CHARACTER","mk_cl_set_macro_character",-1},
  {"SET-PPRINT-DISPATCH","mk_cl_set_pprint_dispatch",-1},
  {"SET-SYNTAX-FROM-CHAR","mk_cl_set_syntax_from_char",-1},
  {"SETF",NULL,-1},
  {"SETQ",NULL,-1},
  {"SEVENTH","mk_cl_seventh",1},
  {"SHADOW","mk_cl_shadow",-1},
  {"SHADOWING-IMPORT","mk_cl_shadowing_import",-1},
  {"SHIFTF",NULL,-1},
  {"SHORT-FLOAT",NULL,-1},
  {"SHORT-FLOAT-EPSILON",NULL,-1},
  {"SHORT-FLOAT-NEGATIVE-EPSILON",NULL,-1},
  {"SHORT-SITE-NAME",NULL,-1},
  {"SIGNAL",NULL,-1},
  {"SIGNED-BYTE",NULL,-1},
  {"SIGNUM","mk_cl_signum",-1},
  {"SIMPLE-ARRAY",NULL,-1},
  {"SIMPLE-BASE-STRING",NULL,-1},
  {"SIMPLE-BIT-VECTOR",NULL,-1},
  {"SIMPLE-BIT-VECTOR-P","mk_cl_simple_bit_vector_p",1},
  {"SIMPLE-CONDITION",NULL,-1},
  {"SIMPLE-CONDITION-FORMAT-CONTROL",NULL,-1},
  {"SIMPLE-CONDITION-FORMAT-ARGUMENTS",NULL,-1},
  {"SIMPLE-ERROR",NULL,-1},
  {"SIMPLE-STRING",NULL,-1},
  {"SIMPLE-STRING-P","mk_cl_simple_string_p",1},
  {"SIMPLE-TYPE-ERROR",NULL,-1},
  {"SIMPLE-VECTOR",NULL,-1},
  {"SIMPLE-VECTOR-P","mk_cl_simple_vector_p",1},
  {"SIMPLE-WARNING",NULL,-1},
  {"SIN","mk_cl_sin",1},
  {"SINGLE-FLOAT",NULL,-1},
  {"SINGLE-FLOAT-EPSILON",NULL,-1},
  {"SINGLE-FLOAT-NEGATIVE-EPSILON",NULL,-1},
  {"SINH","mk_cl_sinh",1},
  {"SIXTH","mk_cl_sixth",1},
  {"SLEEP","mk_cl_sleep",1},
  {"SOFTWARE-TYPE",NULL,-1},
  {"SOFTWARE-VERSION",NULL,-1},
  {"SOME","mk_cl_some",-1},
  {"SORT","mk_cl_sort",-1},
  {"SPACE",NULL,-1},
  {"SPECIAL",NULL,-1},
  {"SPECIAL-OPERATOR-P","mk_cl_special_operator_p",1},
  {"SPEED",NULL,-1},
  {"SQRT","mk_cl_sqrt",1},
  {"STABLE-SORT","mk_cl_stable_sort",-1},
  {"STANDARD-CHAR",NULL,-1},
  {"STANDARD-CHAR-P","mk_cl_standard_char_p",1},
  {"STEP",NULL,-1},
  {"STORAGE-CONDITION",NULL,-1},
  {"STORE-VALUE",NULL,-1},
  {"STREAM",NULL,-1},
  {"STREAM-ELEMENT-TYPE","mk_cl_stream_element_type",1},
  {"STREAM-ERROR",NULL,-1},
  {"STREAM-ERROR-STREAM",NULL,-1},
  {"STREAM-EXTERNAL-FORMAT","mk_cl_stream_external_format",1},
  {"STREAMP","mk_cl_streamp",1},
  {"STRING","mk_cl_string",1},
  {"STRING-DOWNCASE","mk_cl_string_downcase",-1},
  {"STRING-CAPITALIZE","mk_cl_string_capitalize",-1},
  {"STRING-EQUAL","mk_cl_string_equal",-1},
  {"STRING-GREATERP","mk_cl_string_greaterp",-1},
  {"STRING-LEFT-TRIM","mk_cl_string_left_trim",2},
  {"STRING-LESSP","mk_cl_string_lessp",-1},
  {"STRING-NOT-EQUAL","mk_cl_string_not_equal",-1},
  {"STRING-NOT-GREATERP","mk_cl_string_not_greaterp",-1},
  {"STRING-NOT-LESSP","mk_cl_string_not_lessp",-1},
  {"STRING-RIGHT-TRIM","mk_cl_string_right_trim",2},
  {"STRING-STREAM",NULL,-1},
  {"STRING-TRIM","mk_cl_string_trim",2},
  {"STRING-UPCASE","mk_cl_string_upcase",-1},
  {"STRING/=","mk_cl_stringNE",-1},
  {"STRING<","mk_cl_stringL",-1},
  {"STRING<=","mk_cl_stringLE",-1},
  {"STRING=","mk_cl_stringE",-1},
  {"STRING>","mk_cl_stringG",-1},
  {"STRING>=","mk_cl_stringGE",-1},
  {"STRINGP","mk_cl_stringp",1},
  {"STRUCTURE",NULL,-1},
  {"STYLE-WARNING",NULL,-1},
  {"SUBLIS","mk_cl_sublis",-1},
  {"SUBSEQ","mk_cl_subseq",-1},
  {"SUBSETP","mk_cl_subsetp",-1},
  {"SUBST","mk_cl_subst",-1},
  {"SUBST-IF","mk_cl_subst_if",-1},
  {"SUBST-IF-NOT","mk_cl_subst_if_not",-1},
  {"SUBSTITUTE","mk_cl_substitute",-1},
  {"SUBSTITUTE-IF","mk_cl_substitute_if",-1},
  {"SUBSTITUTE-IF-NOT","mk_cl_substitute_if_not",-1},
  {"SUBTYPEP","mk_cl_subtypep",-1},
  {"SVREF","mk_cl_svref",2},
  {"SXHASH","mk_cl_sxhash",1},
  {"SYMBOL",NULL,-1},
  {"SYMBOL-FUNCTION","mk_cl_symbol_function",1},
  {"SYMBOL-MACROLET",NULL,-1},
  {"SYMBOL-NAME","mk_cl_symbol_name",1},
  {"SYMBOL-PACKAGE","mk_cl_symbol_package",1},
  {"SYMBOL-PLIST","mk_cl_symbol_plist",1},
  {"SYMBOL-VALUE","mk_cl_symbol_value",1},
  {"SYMBOLP","mk_cl_symbolp",1},
  {"SYNONYM-STREAM",NULL,-1},
  {"SYNONYM-STREAM-SYMBOL","mk_cl_synonym_stream_symbol",1},
  {"TAGBODY",NULL,-1},
  {"TAILP","mk_cl_tailp",2},
  {"TAN","mk_cl_tan",1},
  {"TANH","mk_cl_tanh",1},
  {"TENTH","mk_cl_tenth",1},
  {"TERPRI","mk_cl_terpri",-1},
  {"THE",NULL,-1},
  {"THIRD","mk_cl_caddr",1},
  {"THROW",NULL,-1},
  {"TIME",NULL,-1},
  {"TRACE",NULL,-1},
  {"TRANSLATE-LOGICAL-PATHNAME","mk_cl_translate_logical_pathname",-1},
  {"TRANSLATE-PATHNAME","mk_cl_translate_pathname",-1},
  {"TREE-EQUAL","mk_cl_tree_equal",-1},
  {"TRUENAME","mk_cl_truename",1},
  {"TRUNCATE","mk_cl_truncate",-1},
  {"TWO-WAY-STREAM",NULL,-1},
  {"TWO-WAY-STREAM-INPUT-STREAM","mk_cl_two_way_stream_input_stream",1},
  {"TWO-WAY-STREAM-OUTPUT-STREAM","mk_cl_two_way_stream_output_stream",1},
  {"TYPE",NULL,-1},
  {"TYPE-ERROR",NULL,-1},
  {"TYPE-ERROR-DATUM",NULL,-1},
  {"TYPE-ERROR-EXPECTED-TYPE",NULL,-1},
  {"TYPE-OF","mk_cl_type_of",1},
  {"TYPECASE",NULL,-1},
  {"TYPEP","mk_cl_typep",-1},
  {"UNBOUND-SLOT",NULL,-1},
  {"UNBOUND-SLOT-INSTANCE",NULL,-1},
  {"UNBOUND-VARIABLE",NULL,-1},
  {"UNDEFINED-FUNCTION",NULL,-1},
  {"UNEXPORT","mk_cl_unexport",-1},
  {"UNINTERN","mk_cl_unintern",-1},
  {"UNION","mk_cl_union",-1},
  {"UNLESS",NULL,-1},
  {"UNREAD-CHAR","mk_cl_unread_char",-1},
  {"UNSIGNED-BYTE",NULL,-1},
  {"UNTRACE",NULL,-1},
  {"UNUSE-PACKAGE","mk_cl_unuse_package",-1},
  {"UNWIND-PROTECT",NULL,-1},
  {"UPGRADED-ARRAY-ELEMENT-TYPE","mk_cl_upgraded_array_element_type",-1},
  {"UPGRADED-COMPLEX-PART-TYPE","mk_cl_upgraded_complex_part_type",-1},
  {"UPPER-CASE-P","mk_cl_upper_case_p",1},
  {"USE-PACKAGE","mk_cl_use_package",-1},
  {"USE-VALUE",NULL,-1},
  {"USER-HOMEDIR-PATHNAME","mk_cl_user_homedir_pathname",-1},
  {"VALUES","mk_cl_values",-1},
  {"VALUES-LIST","mk_cl_values_list",1},
  {"VARIABLE",NULL,-1},
  {"VECTOR","mk_cl_vector",-1},
  {"VECTOR-POP","mk_cl_vector_pop",1},
  {"VECTOR-PUSH","mk_cl_vector_push",2},
  {"VECTOR-PUSH-EXTEND","mk_cl_vector_push_extend",-1},
  {"VECTORP","mk_cl_vectorp",1},
  {"WARN",NULL,-1},
  {"WARNING",NULL,-1},
  {"WHEN",NULL,-1},
  {"WILD-PATHNAME-P","mk_cl_wild_pathname_p",-1},
  {"WITH-COMPILATION-UNIT",NULL,-1},
  {"WITH-CONDITION-RESTARTS",NULL,-1},
  {"WITH-HASH-TABLE-ITERATOR",NULL,-1},
  {"WITH-INPUT-FROM-STRING",NULL,-1},
  {"WITH-OPEN-FILE",NULL,-1},
  {"WITH-OPEN-STREAM",NULL,-1},
  {"WITH-OUTPUT-TO-STRING",NULL,-1},
  {"WITH-PACKAGE-ITERATOR",NULL,-1},
  {"WITH-SIMPLE-RESTART",NULL,-1},
  {"WITH-STANDARD-IO-SYNTAX",NULL,-1},
  {"WRITE","mk_cl_write",-1},
  {"WRITE-BYTE","mk_cl_write_byte",2},
  {"WRITE-CHAR","mk_cl_write_char",-1},
  {"WRITE-LINE","mk_cl_write_line",-1},
  {"WRITE-SEQUENCE","mk_cl_write_sequence",-1},
  {"WRITE-STRING","mk_cl_write_string",-1},
  {"WRITE-TO-STRING","mk_cl_write_to_string",-1},
  {"Y-OR-N-P","mk_cl_y_or_n_p",-1},
  {"YES-OR-NO-P","mk_cl_yes_or_no_p",-1},
  {"ZEROP","mk_cl_zerop",1},

  {"ALLOCATE-INSTANCE",NULL,-1},
  {"ADD-METHOD",NULL,-1},
  {"BUILT-IN-CLASS",NULL,-1},
  {"CALL-METHOD",NULL,-1},
  {"CALL-NEXT-METHOD",NULL,-1},
  {"CHANGE-CLASS",NULL,-1},
  {"CLASS",NULL,-1},
  {"CLASS-NAME",NULL,-1},
  {"CLASS-OF","mk_cl_class_of",1},
  {"COMPUTE-APPLICABLE-METHODS",NULL,-1},
  {"DEFCLASS",NULL,-1},
  {"DEFGENERIC",NULL,-1},
  {"DEFINE-METHOD-COMBINATION",NULL,-1},
  {"DEFMETHOD",NULL,-1},
  {"DESCRIBE-OBJECT",NULL,-1},
  {"ENSURE-GENERIC-FUNCTION",NULL,-1},
  {"FIND-CLASS","mk_cl_find_class",-1},
  {"FIND-METHOD",NULL,-1},
  {"GENERIC-FUNCTION",NULL,-1},
  {"IF",NULL,-1},
  {"INITIALIZE-INSTANCE",NULL,-1},
  {"INVALID-METHOD-ERROR","mk_cl_invalid_method_error",-1},
  {"MAKE-INSTANCE",NULL,-1},
  {"MAKE-INSTANCES-OBSOLETE",NULL,-1},
  {"MAKE-LOAD-FORM",NULL,-1},
  {"MAKE-LOAD-FORM-SAVING-SLOTS",NULL,-1},
  {"MAKE-METHOD",NULL,-1},
  {"METHOD",NULL,-1},
  {"METHOD-COMBINATION-ERROR","mk_cl_method_combination_error",-1},
  {"METHOD-COMBINATION",NULL,-1},
  {"METHOD-QUALIFIERS",NULL,-1},
  {"NEXT-METHOD-P",NULL,-1},
  {"NO-APPLICABLE-METHOD",NULL,-1},
  {"NO-NEXT-METHOD",NULL,-1},
  {"PRINT-OBJECT",NULL,-1},
  {"PRINT-UNREADABLE-OBJECT",NULL,-1},
  {"REINITIALIZE-INSTANCE",NULL,-1},
  {"REMOVE-METHOD",NULL,-1},
  {"SHARED-INITIALIZE",NULL,-1},
  {"SLOT-BOUNDP",NULL,-1},
  {"SLOT-EXISTS-P",NULL,-1},
  {"SLOT-MAKUNBOUND",NULL,-1},
  {"SLOT-MISSING",NULL,-1},
  {"SLOT-UNBOUND",NULL,-1},
  {"SLOT-VALUE",NULL,-1},
  {"STANDARD",NULL,-1},
  {"STANDARD-CLASS",NULL,-1},
  {"STANDARD-GENERIC-FUNCTION",NULL,-1},
  {"STANDARD-METHOD",NULL,-1},
  {"STANDARD-OBJECT",NULL,-1},
  {"STRUCTURE-CLASS",NULL,-1},
  {"STRUCTURE-OBJECT",NULL,-1},
  {"UPDATE-INSTANCE-FOR-DIFFERENT-CLASS",NULL,-1},
  {"UPDATE-INSTANCE-FOR-REDEFINED-CLASS",NULL,-1},
  {"WITH-ACCESSORS",NULL,-1},
  {"WITH-SLOTS",NULL,-1},
  {":" "ARGUMENT-PRECEDENCE-ORDER",NULL,-1},
  {":" "DECLARE",NULL,-1},
  {":" "DEFAULT-INITARGS",NULL,-1},
  {":" "DIRECT-DEFAULT-INITARGS",NULL,-1},
  {":" "DIRECT-SLOTS",NULL,-1},
  {":" "DIRECT-SUPERCLASSES",NULL,-1},
  {":" "GENERIC-FUNCTION-CLASS",NULL,-1},
  {":" "LAMBDA-LIST",NULL,-1},
  {":" "METHOD-CLASS",NULL,-1},
  {":" "METHOD-COMBINATION",NULL,-1},


  {"SI::" "#!",NULL,-1},
  {"SI::" "*BACKQ-LEVEL*",NULL,-1},
  {"SI::" "*CBLOCK*",NULL,-1},
  {"SI::" "*CIRCLE-COUNTER*",NULL,-1},
  {"SI::" "*CIRCLE-STACK*",NULL,-1},
  {"SI::" "*CLASS-NAME-HASH-TABLE*",NULL,-1},
  {"SI::" "*COMPILER-CONSTANTS*",NULL,-1},
  {"SI::" "*GC-MESSAGE*",NULL,-1},
  {"SI::" "*GC-VERBOSE*",NULL,-1},
  {"SI::" "*IGNORE-EOF-ON-TERMINAL-IO*",NULL,-1},
  {"SI::" "*INDENT-FORMATTED-OUTPUT*",NULL,-1},
  {"SI::" "*INIT-FUNCTION-PREFIX*",NULL,-1},
  {"SI::" "*KEEP-DEFINITIONS*",NULL,-1},
  {"SI::" "*LOAD-HOOKS*",NULL,-1},
  {"SI::" "*LOAD-SEARCH-LIST*",NULL,-1},
  {"SI::" "*MAKE-CONSTANT","mk_si_Xmake_constant",2},
  {"SI::" "*MAKE-SPECIAL","mk_si_Xmake_special",1},
  {"SI::" "*PRINT-PACKAGE*",NULL,-1},
  {"SI::" "*PRINT-STRUCTURE*",NULL,-1},
  {"SI::" "*SHARP-EQ-CONTEXT*",NULL,-1},
  {"SI::" "*STEP-LEVEL*",NULL,-1},
  {"SI::" "*STEP-ACTION*",NULL,-1},
  {"SI::" "+READING-FASL-FILE+",NULL,-1},
  {"SI::" ".",NULL,-1},
  {"SI::" "UNQUOTE",NULL,-1},
  {"SI::" "UNQUOTE-NSPLICE",NULL,-1},
  {"SI::" "UNQUOTE-SPLICE",NULL,-1},
  {"SI::" "ALLOCATE-RAW-INSTANCE","mk_si_allocate_raw_instance",3},
  {"SI::" "ARGC","mk_si_argc",0},
  {"SI::" "ARGV","mk_si_argv",1},
  {"SI::" "ASET","mk_si_aset",-1},
  {"SI::" "BASE-CHAR-P","mk_mkcl_base_char_p",1},
  {"SI::" "BASE-STRING-P","mk_si_base_string_p",1},
  {"SI::" "BC-DISASSEMBLE","mk_si_bc_disassemble",1},
  {"SI::" "BC-SPLIT","mk_si_bc_split",1},
  {"SI::" "BDS-TOP","mk_si_bds_top",0},
  {"SI::" "BDS-VAL","mk_si_bds_val",1},
  {"SI::" "BDS-VAR","mk_si_bds_var",1},
  {"SI::" "BIT-ARRAY-OP","mk_si_bit_array_op",4},
  {"SI::" "C-ARGUMENTS-LIMIT",NULL,-1},
  {"SI::" "CHAR-SET","mk_si_char_set",3},
  {"MKCL::" "CHDIR","mk_mkcl_chdir",-1},
  {"SI::" "CLEAR-COMPILER-PROPERTIES","mk_cl_identity",1},
  {"SI::" "COERCE-TO-BASE-STRING","mk_si_coerce_to_base_string",1},
  {"SI::" "COERCE-TO-EXTENDED-STRING","mk_si_coerce_to_extended_string",1},
  {"SI::" "COERCE-TO-FILENAME","mk_si_coerce_to_filename",1},
  {"SI::" "COERCE-TO-FUNCTION","mk_si_coerce_to_function",1},
  {"SI::" "COERCE-TO-PACKAGE","mk_si_coerce_to_package",1},
  {"SI::" "COPY-TO-SIMPLE-BASE-STRING","mk_si_copy_to_simple_base_string",1},
  {"SI::" "COMPILED-FUNCTION-BLOCK","mk_si_compiled_function_block",1},
  {"SI::" "COMPILED-FUNCTION-NAME","mk_si_compiled_function_name",1},
  {"SI::" "COPY-STREAM","mk_si_copy_stream",1},
  {"SI::" "DO-READ-SEQUENCE","mk_si_do_read_sequence",4},
  {"SI::" "DO-WRITE-SEQUENCE","mk_si_do_write_sequence",4},
  {"SI::" "ELT-SET","mk_si_elt_set",3},
  {"SI::" "EVAL-IN-ENV","mk_si_eval_in_env",-1},
  {"SI::" "EXPAND-DEFMACRO",NULL,-1},
  {"SI::" "FILE-COLUMN","mk_si_file_column",1},
  {"SI::" "FILE-KIND","mk_si_file_kind",-1},
  {"SI::" "FILL-POINTER-SET","mk_si_fill_pointer_set",2},
  {"SI::" "FIXNUMP","mk_si_fixnump",1},
  {"SI::" "FORMAT-ERROR",NULL,-1},
  {"SI::" "FORMATTER-AUX",NULL,-1},
  {"SI::" "FRS-BDS","mk_si_frs_bds",1},
  {"SI::" "FRS-IHS","mk_si_frs_ihs",1},
  {"SI::" "FRS-TAG","mk_si_frs_tag",1},
  {"SI::" "FRS-TOP","mk_si_frs_top",0},
  {"SI::" "FSET","mk_si_fset",-1},
  {"SI::" "FUNCTION-BLOCK-NAME","mk_si_function_block_name",1},
  {"SI::" "GET-LIBRARY-PATHNAME","mk_si_get_library_pathname",0},
  {"SI::" "GET-SYSPROP","mk_si_get_sysprop",2},
  {"MKCL::" "GETENV","mk_mkcl_getenv",1},
  {"MKCL::" "GETCWD","mk_mkcl_getcwd",-1},
  {"SI::" "GETPID","mk_si_getpid",0},
  {"SI::" "GETTID","mk_si_gettid",0},
  {"SI::" "HASH-SET","mk_si_hash_set",3},
  {"SI::" "HASH-TABLE-ITERATOR","mk_si_hash_table_iterator",1},
  {"SI::" "IHS-BDS-MARKER","mk_si_ihs_bds_marker",1},
  {"SI::" "IHS-ENV","mk_si_ihs_env",1},
  {"SI::" "IHS-FUN","mk_si_ihs_fun",1},
  {"SI::" "IHS-NEXT","mk_si_ihs_next",1},
  {"SI::" "IHS-PREV","mk_si_ihs_prev",1},
  {"SI::" "IHS-TOP","mk_si_ihs_top",0},
  {"SI::" "INTERPRETER-STACK","mk_si_interpreter_stack",-1},
  {"SI::" "LINK-FROM",NULL,-1},
  {"SI::" "LINK-TO",NULL,-1},
  {"SI::" "LOAD-SOURCE","mk_si_load_source",4},
  {"SI::" "LOGICAL-PATHNAME-P","mk_si_logical_pathname_p",1},
  {"SI::" "MACRO",NULL,-1},
  {"SI::" "MAKE-LAMBDA","mk_si_make_lambda",2},
  {"SI::" "MAKE-PURE-ARRAY","mk_si_make_pure_array",6},
  {"SI::" "MAKE-STRING-OUTPUT-STREAM-FROM-STRING","mk_si_make_string_output_stream_from_string",2},
  {"SI::" "MAKE-STRUCTURE","mk_si_make_structure",-1},
  {"SI::" "MAKE-VECTOR","mk_si_make_vector",6},
  {"SI::" "MANGLE-NAME","mk_si_mangle_name",1},
  {"SI::" "MEMBER1","mk_si_member1",5},
  {"SI::" "MEMQ","mk_si_memq",2},
  {"SI::" "MKDIR","mk_si_mkdir",2},
  {"SI::" "MKSTEMP","mk_si_mkstemp",-1},
  {"SI::" "RMDIR","mk_si_rmdir",1},
  {"MKCL::" "MAKE-PIPE","mk_mkcl_make_pipe",0},
  {"SI::" "PACKAGE-HASH-TABLES","mk_si_package_hash_tables",1},
  {"SI::" "PATHNAME-TRANSLATIONS","mk_si_pathname_translations",-1},
  {"SI::" "ALL-LOGICAL-PATHNAME-TRANSLATIONS","mk_si_all_logical_pathname_translations",0},
  {"SI::" "POINTER","mk_si_pointer",1},
  {"SI::" "PRETTY-PRINT-FORMAT",NULL,-1},
  {"SI::" "PROCESS-DECLARATIONS","mk_si_process_declarations",-1},



  {"SI::" "PROCESS-LAMBDA-LIST","mk_si_process_lambda_list",2},
  {"SI::" "PUT-F","mk_si_put_f",3},
  {"SI::" "PUT-PROPERTIES","mk_si_put_properties",-1},
  {"SI::" "PUT-SYSPROP","mk_si_put_sysprop",3},
  {"SI::" "PUTPROP","mk_si_putprop",3},
  {"SI::" "READTABLE-CASE-SET","mk_si_readtable_case_set",2},
  {"SI::" "REM-F","mk_si_rem_f",2},
  {"SI::" "REM-SYSPROP","mk_si_rem_sysprop",2},
  {"SI::" "REPLACE-ARRAY","mk_si_replace_array",2},
  {"SI::" "ROW-MAJOR-ASET","mk_si_row_major_aset",3},
  {"SI::" "RUN-COMMAND","mk_si_run_command",-1},
  {"MKCL::" "RUN-PROGRAM","mk_mkcl_run_program",-1},
  {"SI::" "SAFE-EVAL","mk_si_safe_eval",-1},
  {"SI::" "SCH-FRS-BASE","mk_si_sch_frs_base",2},
  {"SI::" "SCHAR-SET","mk_si_char_set",3},
  {"SI::" "SHARP-A-READER",NULL,-1},
  {"SI::" "SHARP-S-READER",NULL,-1},
  {"SI::" "SELECT-PACKAGE","mk_si_select_package",1},
  {"SI::" "SET-SYMBOL-PLIST","mk_si_set_symbol_plist",2},
  {"MKCL::" "SETENV","mk_mkcl_setenv",2},
  {"SI::" "SETF-LAMBDA",NULL,-1},
  {"SI::" "SETF-METHOD",NULL,-1},
  {"SI::" "SETF-NAMEP",NULL,-1},
  {"SI::" "SETF-SYMBOL",NULL,-1},
  {"SI::" "SETF-UPDATE",NULL,-1},
  {"SI::" "SIMPLE-PROGRAM-ERROR",NULL,-1},
  {"SI::" "SPECIALP","mk_si_specialp",1},
  {"SI::" "STANDARD-READTABLE","mk_si_standard_readtable",0},
  {"SI::" "STEPPER",NULL,-1},
  {"SI::" "CONCATENATE-BASE-STRINGS","mk_si_concatenate_base_strings",-1},
  {"SI::" "FAST-READ-FROM-BASE-STRING","mk_si_fast_read_from_base_string",1},
  {"SI::" "STRUCTURE-NAME","mk_si_structure_name",1},
  {"SI::" "STRUCTURE-LENGTH","mk_si_structure_length",1},
  {"SI::" "STRUCTURE-PRINT-FUNCTION",NULL,-1},
  {"SI::" "STRUCTURE-REF","mk_si_structure_ref",3},
  {"SI::" "STRUCTURE-SET","mk_si_structure_set",4},
  {"SI::" "STRUCTURE-SLOT-DESCRIPTIONS",NULL,-1},
  {"SI::" "STRUCTURE-SUBTYPE-P","mk_si_structure_subtype_p",2},
  {"SI::" "STRUCTUREP","mk_si_structurep",1},
  {"SI::" "SVSET","mk_si_svset",3},
  {"SI::" "SYMBOL-MACRO",NULL,-1},
  {"SI::" "SYSTEM","mk_si_system",-1},
  {"SI::" "TERMINAL-INTERRUPT",NULL,-1},
  {"SI::" "SIGINT-HANDLER",NULL,-1},
  {"SI::" "SIGHUP-HANDLER",NULL,-1},
  {"SI::" "SIGTERM-HANDLER",NULL,-1},
  {"SI::" "TERMINAL-SIGNAL-HANDLER",NULL,-1},
  {"SI::" "INITIAL",NULL,-1},
  {"SI::" "TOP-LEVEL",NULL,-1},
  {"SI::" "UNIVERSAL-ERROR-HANDLER",NULL,-1},
  {"SI::" "VALID-FUNCTION-NAME-P","mk_si_valid_function_name_p",1},
  {"SI::" "WRITE-OBJECT","mk_si_write_object",2},
  {"SI::" "WRITE-UGLY-OBJECT","mk_si_write_ugly_object",2},

  {"SI::" "STRUCTURE-INCLUDE",NULL,-1},
  {"SI::" "COPY-INSTANCE","mk_si_copy_instance",1},
  {"SI::" "GENERIC-FUNCTION-P","mk_si_generic_function_p",1},
  {"SI::" "INSTANCE-REF-SAFE","mk_si_instance_ref_safe",2},
  {"SI::" "INSTANCE-REF","mk_si_instance_ref",2},
  {"SI::" "INSTANCE-SET","mk_si_instance_set",3},
  {"SI::" "INSTANCE-SIG","mk_si_instance_sig",1},
  {"SI::" "INSTANCE-SIG-SET","mk_si_instance_sig_set",1},
  {"SI::" "INSTANCE-SIG-SET2","mk_si_instance_sig_set2",2},
  {"SI::" "INSTANCE-CLASS","mk_si_instance_class",1},
  {"SI::" "INSTANCE-CLASS-SET","mk_si_instance_class_set",2},
  {"SI::" "INSTANCEP","mk_si_instancep",1},
  {"SI::" "INSTANCE-LENGTH","mk_si_instance_length",1},
  {"SI::" "SL-BOUNDP","mk_si_sl_boundp",1},
  {"SI::" "SL-MAKUNBOUND","mk_si_sl_makunbound",2},
  {"SI::" "SUBCLASSP","mk_si_subclassp",2},
  {"SI::" "OF-CLASS-P","mk_si_of_class_p",2},

  {"SI::" "*SOURCE-LOCATION*",NULL,-1},
  {"SI::" "*REGISTER-WITH-PDE-HOOK*",NULL,-1},
  {"SI::" "REGISTER-WITH-PDE",NULL,-1},



  {":" "ADJUSTABLE",NULL,-1},
  {":" "ABORT",NULL,-1},
  {":" "ABSOLUTE",NULL,-1},
  {":" "ALLOW-OTHER-KEYS",NULL,-1},
  {":" "APPEND",NULL,-1},
  {":" "ARRAY",NULL,-1},
  {":" "BACK",NULL,-1},
  {":" "BASE",NULL,-1},
  {":" "BLOCK",NULL,-1},
  {":" "CAPITALIZE",NULL,-1},
  {":" "CASE",NULL,-1},
  {":" "CIRCLE",NULL,-1},
  {":" "COMPILE-TOPLEVEL",NULL,-1},
  {":" "COMMON",NULL,-1},
  {":" "CONC-NAME",NULL,-1},
  {":" "CONSTRUCTOR",NULL,-1},
  {":" "CONTROL-STRING",NULL,-1},
  {":" "COPIER",NULL,-1},
  {":" "CREATE",NULL,-1},
  {":" "DATUM",NULL,-1},
  {":" "DEFAULT",NULL,-1},
  {":" "DEFAULTS",NULL,-1},
  {":" "DEVICE",NULL,-1},
  {":" "DIRECTION",NULL,-1},
  {":" "DIRECTORY",NULL,-1},
  {":" "DISPLACED-INDEX-OFFSET",NULL,-1},
  {":" "DISPLACED-TO",NULL,-1},
  {":" "DOCUMENTATION",NULL,-1},
  {":" "DOWNCASE",NULL,-1},
  {":" "ELEMENT-TYPE",NULL,-1},
  {":" "END",NULL,-1},
  {":" "END1",NULL,-1},
  {":" "END2",NULL,-1},
  {":" "EOF",NULL,-1},
  {":" "ERROR",NULL,-1},
  {":" "ESCAPE",NULL,-1},
  {":" "EXECUTE",NULL,-1},
  {":" "EXPECTED-TYPE",NULL,-1},
  {":" "EXPORT",NULL,-1},
  {":" "EXPORT-FROM",NULL,-1},
  {":" "EXTERNAL",NULL,-1},
  {":" "EXTERNAL-FORMAT",NULL,-1},
  {":" "FILE",NULL,-1},
  {":" "FILL-POINTER",NULL,-1},
  {":" "FORCE",NULL,-1},
  {":" "FORMAT-ARGUMENTS",NULL,-1},
  {":" "FORMAT-CONTROL",NULL,-1},
  {":" "FUNCTION",NULL,-1},
  {":" "GENSYM",NULL,-1},
  {":" "HOST",NULL,-1},
  {":" "IF-DOES-NOT-EXIST",NULL,-1},
  {":" "IF-EXISTS",NULL,-1},
  {":" "IMPORT-FROM",NULL,-1},
  {":" "INCLUDE",NULL,-1},
  {":" "INHERITED",NULL,-1},
  {":" "INITIAL-ELEMENT",NULL,-1},
  {":" "INITIAL-CONTENTS",NULL,-1},
  {":" "INITIAL-OFFSET",NULL,-1},
  {":" "INPUT",NULL,-1},
  {":" "INTERACTIVE",NULL,-1},
  {":" "INSTANCE",NULL,-1},
  {":" "INTERN",NULL,-1},
  {":" "INTERNAL",NULL,-1},
  {":" "INVERT",NULL,-1},
  {":" "IO",NULL,-1},
  {":" "JUNK-ALLOWED",NULL,-1},
  {":" "KEY",NULL,-1},
  {":" "LENGTH",NULL,-1},
  {":" "LEVEL",NULL,-1},
  {":" "LINES",NULL,-1},
  {":" "LINK",NULL,-1},
  {":" "LIST-ALL",NULL,-1},
  {":" "LOCAL",NULL,-1},
  {":" "LOCKABLE",NULL,-1},
  {":" "LOAD-TOPLEVEL",NULL,-1},
  {":" "MISER-WIDTH",NULL,-1},
  {":" "NAME",NULL,-1},
  {":" "NAMED",NULL,-1},
  {":" "NEW-VERSION",NULL,-1},
  {":" "NEWEST",NULL,-1},
  {":" "NICKNAMES",NULL,-1},
  {":" "OBJECT",NULL,-1},
  {":" "OFFSET",NULL,-1},
  {":" "OPERATION",NULL,-1},
  {":" "OPERANDS",NULL,-1},
  {":" "OUTPUT",NULL,-1},
  {":" "OVERWRITE",NULL,-1},
  {":" "PACKAGE",NULL,-1},
  {":" "PATHNAME",NULL,-1},
  {":" "PPRINT-DISPATCH",NULL,-1},
  {":" "PREDICATE",NULL,-1},
  {":" "PRESERVE",NULL,-1},
  {":" "PRETTY",NULL,-1},
  {":" "PRINT",NULL,-1},
  {":" "PRINT-FUNCTION",NULL,-1},
  {":" "PRINT-OBJECT",NULL,-1},
  {":" "PROBE",NULL,-1},
  {":" "RADIX",NULL,-1},
  {":" "READABLY",NULL,-1},
  {":" "REHASH-SIZE",NULL,-1},
  {":" "REHASH-THRESHOLD",NULL,-1},
  {":" "RELATIVE",NULL,-1},
  {":" "RENAME",NULL,-1},
  {":" "RENAME-AND-DELETE",NULL,-1},
  {":" "REPORT",NULL,-1},
  {":" "RIGHT-MARGIN",NULL,-1},
  {":" "SET-DEFAULT-PATHNAME",NULL,-1},
  {":" "SEARCH-LIST",NULL,-1},
  {":" "SHADOW",NULL,-1},
  {":" "SHADOWING-IMPORT",NULL,-1},
  {":" "SIZE",NULL,-1},
  {":" "SPECIAL",NULL,-1},
  {":" "START",NULL,-1},
  {":" "START1",NULL,-1},
  {":" "START2",NULL,-1},
  {":" "STREAM",NULL,-1},
  {":" "SUPERSEDE",NULL,-1},
  {":" "TAG",NULL,-1},
  {":" "TEST",NULL,-1},
  {":" "TEST-NOT",NULL,-1},
  {":" "TYPE",NULL,-1},
  {":" "UNSPECIFIC",NULL,-1},
  {":" "UP",NULL,-1},
  {":" "UPCASE",NULL,-1},
  {":" "USE",NULL,-1},
  {":" "STDIO-STREAM",NULL,-1},
  {":" "VERBOSE",NULL,-1},
  {":" "VERSION",NULL,-1},
  {":" "WILD",NULL,-1},
  {":" "WILD-INFERIORS",NULL,-1},
  {":" "WAIT",NULL,-1},

  {"MKCL::" "BYTE8",NULL,-1},
  {"MKCL::" "BYTE16",NULL,-1},
  {"MKCL::" "BYTE32",NULL,-1},
  {"MKCL::" "BYTE64",NULL,-1},
  {"MKCL::" "COMPILER-LET",NULL,-1},
  {"MKCL::" "INTEGER8",NULL,-1},
  {"MKCL::" "INTEGER16",NULL,-1},
  {"MKCL::" "INTEGER32",NULL,-1},
  {"MKCL::" "INTEGER64",NULL,-1},
  {"MKCL::" "QUIT",NULL,-1},
  {"SI::" "LAMBDA-BLOCK",NULL,-1},
  {"SI::" "INSTANCE",NULL,-1},

  {"SI::" "ALLOCATE-FOREIGN-DATA","mk_si_allocate_foreign_data",2},
  {"SI::" "FIND-FOREIGN-SYMBOL","mk_si_find_foreign_symbol",4},



  {"SI::" "FOREIGN",NULL,-1},

  {"SI::" "FOREIGN-ADDRESS","mk_si_foreign_address",1},
  {"SI::" "FOREIGN-INDEXED","mk_si_foreign_indexed",4},
  {"SI::" "FOREIGN-RECAST","mk_si_foreign_recast",3},
  {"SI::" "FOREIGN-REF","mk_si_foreign_ref",4},
  {"SI::" "FOREIGN-REF-ELT","mk_si_foreign_ref_elt",3},
  {"SI::" "FOREIGN-SET","mk_si_foreign_set",3},
  {"SI::" "FOREIGN-SET-ELT","mk_si_foreign_set_elt",4},
  {"SI::" "FOREIGN-TAG","mk_si_foreign_tag",1},
  {"SI::" "FREE-FOREIGN-DATA","mk_si_free_foreign_data",1},
  {"SI::" "MAKE-FOREIGN-DATA-FROM-ARRAY","mk_si_make_foreign_data_from_array",1},
  {"SI::" "LOAD-FOREIGN-MODULE","mk_si_load_foreign_module",1},
  {"SI::" "UNLOAD-FOREIGN-MODULE","mk_si_unload_foreign_module",1},
  {"SI::" "NULL-POINTER-P","mk_si_null_pointer_p",1},
  {"SI::" "SIZE-OF-FOREIGN-ELT-TYPE","mk_si_size_of_foreign_elt_type",1},
  {":" "BYTE",NULL,-1},
  {":" "CHAR",NULL,-1},
  {":" "CSTRING",NULL,-1},
  {":" "DOUBLE",NULL,-1},
  {":" "FIXNUM",NULL,-1},
  {":" "FLOAT",NULL,-1},
  {":" "INT",NULL,-1},
  {":" "INT8-T",NULL,-1},
  {":" "INT16-T",NULL,-1},
  {":" "INT32-T",NULL,-1},
  {":" "INT64-T",NULL,-1},
  {":" "LONG",NULL,-1},
  {":" "LONG-DOUBLE",NULL,-1},
  {":" "LONG-LONG",NULL,-1},
  {":" "POINTER-SELF",NULL,-1},
  {":" "POINTER-VOID",NULL,-1},
  {":" "SHORT",NULL,-1},
  {":" "STRUCT",NULL,-1},
  {":" "UNION",NULL,-1},
  {":" "VOID",NULL,-1},
  {":" "UINT8-T",NULL,-1},
  {":" "UINT16-T",NULL,-1},
  {":" "UINT32-T",NULL,-1},
  {":" "UINT64-T",NULL,-1},
  {":" "UNSIGNED-BYTE",NULL,-1},
  {":" "UNSIGNED-CHAR",NULL,-1},
  {":" "UNSIGNED-INT",NULL,-1},
  {":" "UNSIGNED-LONG",NULL,-1},
  {":" "UNSIGNED-LONG-LONG",NULL,-1},
  {":" "UNSIGNED-SHORT",NULL,-1},
  {":" "FLOAT-COMPLEX",NULL,-1},
  {":" "DOUBLE-COMPLEX",NULL,-1},
  {":" "LONG-DOUBLE-COMPLEX",NULL,-1},
  {":" "FLOAT-IMAGINARY",NULL,-1},
  {":" "DOUBLE-IMAGINARY",NULL,-1},
  {":" "LONG-DOUBLE-IMAGINARY",NULL,-1},
  {"SI::" "C-CHAR-BIT",NULL,-1},
  {"SI::" "C-CHAR-MAX",NULL,-1},
  {"SI::" "C-CHAR-MIN",NULL,-1},
  {"SI::" "C-INT-MAX",NULL,-1},
  {"SI::" "C-INT-MIN",NULL,-1},
  {"SI::" "C-SHORT-MAX",NULL,-1},
  {"SI::" "C-SHORT-MIN",NULL,-1},
  {"SI::" "C-LONG-MAX",NULL,-1},
  {"SI::" "C-LONG-MIN",NULL,-1},
  {"SI::" "C-LONG-LONG-MAX",NULL,-1},
  {"SI::" "C-LONG-LONG-MIN",NULL,-1},
  {"SI::" "C-UCHAR-MAX",NULL,-1},
  {"SI::" "C-UINT-MAX",NULL,-1},
  {"SI::" "C-USHORT-MAX",NULL,-1},
  {"SI::" "C-ULONG-MAX",NULL,-1},
  {"SI::" "C-ULONG-LONG-MAX",NULL,-1},
  {"SI::" "GC","mk_si_gc",-1},
  {"SI::" "GC-DUMP","mk_si_gc_dump",0},

  {"MT::" "THREAD",NULL,-1},
  {"MT::" "LOCK",NULL,-1},
  {"MT::" "RWLOCK",NULL,-1},
  {"MT::" "SEMAPHORE",NULL,-1},
  {"MT::" "CONDITION-VARIABLE",NULL,-1},
  {"MT::" "*THREAD*",NULL,-1},
  {"MT::" "ALL-THREADS","mk_mt_all_threads",0},
  {"MT::" "EXIT-THREAD","mk_mt_exit_thread",1},
  {"MT::" "TERMINATE-THREAD","mk_mt_terminate_thread",0},
  {"MT::" "MAKE-THREAD","mk_mt_make_thread",-1},
  {"MT::" "THREAD-ACTIVE-P","mk_mt_thread_active_p",1},
  {"MT::" "THREAD-ENABLE","mk_mt_thread_enable",1},
  {"MT::" "THREAD-YIELD","mk_mt_thread_yield",0},
  {"MT::" "THREAD-KILL","mk_mt_thread_kill",1},
  {"MT::" "THREAD-DETACH","mk_mt_thread_detach",1},
  {"MT::" "THREAD-JOIN","mk_mt_thread_join",1},
  {"MT::" "THREAD-NAME","mk_mt_thread_name",1},
  {"MT::" "THREAD-PRESET","mk_mt_thread_preset",-1},
  {"MT::" "SHOW-SIGMASK","mk_mt_show_sigmask",0},
  {"MT::" "RESET-SIGMASK","mk_mt_reset_sigmask",0},
  {"MT::" "BLOCK-SIGNALS","mk_mt_block_signals",0},
  {"MT::" "UNBLOCK-SIGNALS","mk_mt_unblock_signals",0},
  {"MT::" "THREAD-RUN-FUNCTION","mk_mt_thread_run_function",-1},



  {"MT::" "MAKE-LOCK","mk_mt_make_lock",-1},
  {":" "RECURSIVE",NULL,-1},
  {"MT::" "RECURSIVE-LOCK-P","mk_mt_recursive_lock_p",1},
  {"MT::" "LOCK-NAME","mk_mt_lock_name",1},
  {"MT::" "LOCK-HOLDER","mk_mt_lock_holder",1},
  {"MT::" "GET-LOCK","mk_mt_get_lock",-1},
  {":" "TIMEOUT",NULL,-1},
  {"MT::" "GIVEUP-LOCK","mk_mt_giveup_lock",1},
  {"MT::" "MAKE-RWLOCK","mk_mt_make_rwlock",0},
  {"MT::" "GIVEUP-RWLOCK","mk_mt_giveup_rwlock",-1},
  {"MT::" "GET-READ-RWLOCK","mk_mt_get_read_rwlock",-1},
  {"MT::" "GET-WRITE-RWLOCK","mk_mt_get_write_rwlock",-1},
  {"MT::" "MAKE-SEMAPHORE","mk_mt_make_semaphore",-1},
  {"MT::" "SEMAPHORE-COUNT","mk_mt_semaphore_count",1},
  {"MT::" "SEMAPHORE-SIGNAL","mk_mt_semaphore_signal",-1},
  {"MT::" "SEMAPHORE-WAIT","mk_mt_semaphore_wait",-1},
  {"MT::" "MAKE-CONDITION-VARIABLE","mk_mt_make_condition_variable",0},
  {"MT::" "CONDITION-WAIT","mk_mt_condition_wait",-1},
  {"MT::" "CONDITION-SIGNAL","mk_mt_condition_signal",1},
  {"MT::" "CONDITION-BROADCAST","mk_mt_condition_broadcast",1},
  {":" "INITIAL-BINDINGS",NULL,-1},
  {"MT::" "INTERRUPT-THREAD","mk_mt_interrupt_thread",-1},
  {"MT::" "+LOAD-COMPILE-LOCK+",NULL,-1},
  {"MT::" "WITH-LOCK",NULL,-1},
  {"MT::" "WITHOUT-LOCK",NULL,-1},
  {"MT::" "WITHOUT-INTERRUPTS",NULL,-1},

  {"MT::" "INTERRUPT-ERROR",NULL,-1},
  {"MT::" "THREAD-SLEEPING",NULL,-1},
  {"MT::" "INTERRUPT-REFUSED",NULL,-1},
  {"MT::" "INVALID-THREAD",NULL,-1},

  {"SI::" "WHILE",NULL,-1},
  {"SI::" "UNTIL",NULL,-1},
  {"SI::" "QUASIQUOTE",NULL,-1},
  {"SI::" "*EXIT-HOOKS*",NULL,-1},
  {":" "THREAD",NULL,-1},
  {":" "REASON",NULL,-1},
  {":" "SUSPENDED",NULL,-1},
  {":" "DEAD",NULL,-1},

  {"CLOS::" "*BUILTIN-CLASSES*",NULL,-1},
  {"CLOS::" "COMPUTE-EFFECTIVE-METHOD",NULL,-1},
  {"CLOS::" "COMPUTE-EFFECTIVE-METHOD-FOR-CACHE",NULL,-1},
  {"CLOS::" "FUNCALLABLE-STANDARD-INSTANCE-ACCESS","mk_si_instance_ref",2},
  {"CLOS::" "SET-FUNCALLABLE-INSTANCE-FUNCTION","mk_clos_set_funcallable_instance_function",2},

  {"SI::" "CL-WORD-BITS",NULL,-1},
  {"MKCL::" "CL-WORD",NULL,-1},
  {"MKCL::" "CL-INDEX",NULL,-1},

  {"SI::" "DO-DEFTYPE","mk_si_do_deftype",-1},
  {"SI::" "CREATE-TYPE-NAME",NULL,-1},
  {"SI::" "*ALIEN-DECLARATIONS*",NULL,-1},

  {"SI::" "LOAD-BINARY","mk_si_load_binary",4},

  {"SI::" "*CODE-WALKER*",NULL,-1},

  {"SI::" "CALL-CFUN","mk_si_call_cfun",-1},
  {":" "CALLBACK",NULL,-1},
  {"SI::" "MAKE-DYNAMIC-CALLBACK","mk_si_make_dynamic_callback",-1},
  {":" "CDECL",NULL,-1},
  {":" "STDCALL",NULL,-1},

  {"SI::" "TRAP-FPE",NULL,-1},

  {"SI::" "DO-SIGSEGV","mk_si_do_sigsegv",0},
  {"SI::" "OBJNULL","mk_si_objnull",0},

  {"SI::" "DISPLAY-SIGNAL-DISPOSITIONS","mk_si_display_signal_dispositions",0},

  {"SI::" "*ACTION-ON-UNDEFINED-VARIABLE*",NULL,-1},

  {"SI::" "SET-BUFFERING-MODE","mk_si_set_buffering_mode",2},
  {":" "NONE",NULL,-1},
  {":" "LINE-BUFFERED",NULL,-1},
  {":" "LINE",NULL,-1},
  {":" "FULLY-BUFFERED",NULL,-1},
  {":" "FULL",NULL,-1},

  {"SI::" "CMP-ENV-REGISTER-MACROLET",NULL,-1},

  {"SI::" "GET-FINALIZER","mk_si_get_finalizer",1},
  {"SI::" "SET-FINALIZER","mk_si_set_finalizer",2},

  {"SI::" "*RELATIVE-PACKAGE-NAMES*",NULL,-1},
  {":" "RELATIVE-PACKAGE-NAMES",NULL,-1},
  {"SI::" "FIND-RELATIVE-PACKAGE","mk_si_find_relative_package",-1},
  {"SI::" "PACKAGE-PARENT","mk_si_package_parent",-1},
  {"SI::" "PACKAGE-CHILDREN","mk_si_package_children",-1},

  {"SI::" "WRONG-TYPE-ARGUMENT",NULL,-1},

  {"SI::" "GC-STATS","mk_si_gc_stats",1},

  {"SI::" "*CURRENT-FORM*",NULL,-1},

  {"SI::" "CODE-BLOCK",NULL,-1},

  {"SI::" "CLEAR-GFUN-CACHE","mk_si_clear_gfun_cache",1},

  {"SI::" "TEMP-STACK-FRAME",NULL,-1},
  {"SI::" "APPLY-FROM-TEMP-STACK-FRAME","mk_si_apply_from_temp_stack_frame",2},

  {"GRAY::" "CLOSE",NULL,-1},
  {"GRAY::" "STREAMP",NULL,-1},
  {"GRAY::" "INPUT-STREAM-P",NULL,-1},
  {"GRAY::" "OUTPUT-STREAM-P",NULL,-1},
  {"GRAY::" "OPEN-STREAM-P",NULL,-1},
  {"GRAY::" "STREAM-ADVANCE-TO-COLUMN",NULL,-1},
  {"GRAY::" "STREAM-CLEAR-INPUT",NULL,-1},
  {"GRAY::" "STREAM-CLEAR-OUTPUT",NULL,-1},
  {"GRAY::" "STREAM-ELEMENT-TYPE",NULL,-1},
  {"GRAY::" "STREAM-FILE-POSITION",NULL,-1},
  {"GRAY::" "STREAM-FINISH-OUTPUT",NULL,-1},
  {"GRAY::" "STREAM-FORCE-OUTPUT",NULL,-1},
  {"GRAY::" "STREAM-FRESH-LINE",NULL,-1},
  {"GRAY::" "STREAM-INTERACTIVE-P",NULL,-1},
  {"GRAY::" "STREAM-LINE-COLUMN",NULL,-1},
  {"GRAY::" "STREAM-LISTEN",NULL,-1},
  {"GRAY::" "STREAM-PEEK-CHAR",NULL,-1},
  {"GRAY::" "STREAM-READ-BYTE",NULL,-1},
  {"GRAY::" "STREAM-READ-CHAR",NULL,-1},
  {"GRAY::" "STREAM-READ-CHAR-NO-HANG",NULL,-1},
  {"GRAY::" "STREAM-READ-LINE",NULL,-1},
  {"GRAY::" "STREAM-READ-SEQUENCE",NULL,-1},
  {"GRAY::" "STREAM-START-LINE-P",NULL,-1},
  {"GRAY::" "STREAM-TERPRI",NULL,-1},
  {"GRAY::" "STREAM-UNREAD-CHAR",NULL,-1},
  {"GRAY::" "STREAM-WRITE-BYTE",NULL,-1},
  {"GRAY::" "STREAM-WRITE-CHAR",NULL,-1},
  {"GRAY::" "STREAM-WRITE-SEQUENCE",NULL,-1},
  {"GRAY::" "STREAM-WRITE-STRING",NULL,-1},
  {"GRAY::" "FUNDAMENTAL-STREAM",NULL,-1},
  {"GRAY::" "FUNDAMENTAL-INPUT-STREAM",NULL,-1},
  {"GRAY::" "FUNDAMENTAL-OUTPUT-STREAM",NULL,-1},
  {"GRAY::" "FUNDAMENTAL-CHARACTER-STREAM",NULL,-1},
  {"GRAY::" "FUNDAMENTAL-BINARY-STREAM",NULL,-1},
  {"GRAY::" "FUNDAMENTAL-CHARACTER-INPUT-STREAM",NULL,-1},
  {"GRAY::" "FUNDAMENTAL-CHARACTER-OUTPUT-STREAM",NULL,-1},
  {"GRAY::" "FUNDAMENTAL-BINARY-INPUT-STREAM",NULL,-1},
  {"GRAY::" "FUNDAMENTAL-BINARY-OUTPUT-STREAM",NULL,-1},

  {"SI::" "LOG1P","mk_si_log1p",1},

  {"SI::" "COMPILED-FUNCTION-FILE","mk_si_compiled_function_file",1},

  {"SI::" "PROPERTY-LIST",NULL,-1},

  {"SI::" "BYTECODE",NULL,-1},

  {"SI::" "HASH-EQL","mk_si_hash_eql",-1},
  {"SI::" "HASH-EQUAL","mk_si_hash_equal",-1},
  {"SI::" "HASH-EQUALP","mk_si_hash_equalp",-1},

  {"MKCL::" "INTERACTIVE-INTERRUPT",NULL,-1},

  {"MKCL::" "STORAGE-EXHAUSTED",NULL,-1},
  {"MKCL::" "STACK-OVERFLOW",NULL,-1},
  {"MKCL::" "STACK-OVERFLOW-SIZE",NULL,-1},
  {"MKCL::" "STACK-OVERFLOW-TYPE",NULL,-1},
  {"SI::" "BINDING-STACK",NULL,-1},
  {"SI::" "FRAME-STACK",NULL,-1},
  {"SI::" "LISP-TEMP-STACK",NULL,-1},
  {"SI::" "CALL-STACK",NULL,-1},
  {"SI::" "HEAP-SIZE",NULL,-1},




  {"MKCL::" "SEGMENTATION-VIOLATION",NULL,-1},
  {"MKCL::" "SEGMENTATION-VIOLATION-ADDRESS",NULL,-1},

  {":" "ADDRESS",NULL,-1},

  {"MKCL::" "EXTENDED-STRING",NULL,-1},

  {":" "LATIN-1",NULL,-1},
  {":" "ISO-8859-1",NULL,-1},
  {":" "UTF-8",NULL,-1},
  {":" "UCS-2",NULL,-1},
  {":" "UCS-4",NULL,-1},

  {"SI::" "CONSTANTLY-T",NULL,-1},
  {"SI::" "CONSTANTLY-NIL",NULL,-1},

  {"SI::" "MAYBE-QUOTE",NULL,-1},
  {"SI::" "MAYBE-UNQUOTE",NULL,-1},

  {":" "CR",NULL,-1},
  {":" "LF",NULL,-1},
  {":" "CRLF",NULL,-1},
  {":" "UCS-2BE",NULL,-1},
  {":" "UCS-4BE",NULL,-1},
  {":" "UCS-2LE",NULL,-1},
  {":" "UCS-4LE",NULL,-1},

  {"SI::" "LOAD-ENCODING",NULL,-1},
  {"SI::" "MAKE-ENCODING",NULL,-1},
  {"SI::" "ALL-ENCODINGS",NULL,-1},

  {":" "US-ASCII",NULL,-1},
  {":" "LITTLE-ENDIAN",NULL,-1},
  {":" "BIG-ENDIAN",NULL,-1},

  {"SI::" "+UNICODE-DATABASE+",NULL,-1},

  {"SI::" "COPY-FILE","mk_si_copy_file",2},

  {"SI::" "FILL-ARRAY-WITH-ELT","mk_si_fill_array_with_elt",4},

  {"SI::" "+MKCL-VERSION-NUMBER+",NULL,-1},

  {"SI::" "*BYTECODE-COMPILER*",NULL,-1},

  {"MKCL::" "SHORT-FLOAT-POSITIVE-INFINITY",NULL,-1},
  {"MKCL::" "SINGLE-FLOAT-POSITIVE-INFINITY",NULL,-1},
  {"MKCL::" "DOUBLE-FLOAT-POSITIVE-INFINITY",NULL,-1},
  {"MKCL::" "LONG-FLOAT-POSITIVE-INFINITY",NULL,-1},
  {"MKCL::" "SHORT-FLOAT-NEGATIVE-INFINITY",NULL,-1},
  {"MKCL::" "SINGLE-FLOAT-NEGATIVE-INFINITY",NULL,-1},
  {"MKCL::" "DOUBLE-FLOAT-NEGATIVE-INFINITY",NULL,-1},
  {"MKCL::" "LONG-FLOAT-NEGATIVE-INFINITY",NULL,-1},
  {"SI::" "FLOAT-NAN-P","mk_si_float_nan_p",1},
  {"SI::" "FLOAT-INFINITY-P","mk_si_float_infinity_p",1},

  {"SI::" "READ-OBJECT-OR-IGNORE","mk_si_read_object_or_ignore",2},

  {"SI::" "OUTPUT-FLOAT-NAN",NULL,-1},
  {"SI::" "OUTPUT-FLOAT-INFINITY",NULL,-1},

  {"SI::" "UNBOUND-VALUE-P","mk_si_unbound_value_p",1},

  {"SI::" "PACKAGES-IN-WAITING","mk_si_packages_in_waiting",0},

  {"SI::" "HASH-TABLES-STATISTICS","mk_si_hash_tables_statistics",0},

  {":" "MKCL-COMPILED",NULL,-1},

  {"SI::" "+MKCL-FASL-VERSION+",NULL,-1},

  {":" "LINUX",NULL,-1},
  {":" "LINUX_2.6",NULL,-1},
  {":" "WINDOWS",NULL,-1},
  {":" "WIN32",NULL,-1},
  {":" "WIN64",NULL,-1},
  {":" "WINNT",NULL,-1},
  {":" "WIN2K",NULL,-1},
  {":" "WINXP",NULL,-1},
  {":" "WINVS",NULL,-1},
  {":" "WIN7",NULL,-1},

  {":" "X86",NULL,-1},
  {":" "X86-64",NULL,-1},

  {"SI::" "MEM-STATS","mk_si_mem_stats",0},

  {"SI::" "CLOSUREP","mk_si_closurep",1},
  {"SI::" "CLOSURE-ENV","mk_si_closure_env",1},
  {"SI::" "CLOSURE-PRODUCER","mk_si_closure_producer",1},
  {"SI::" "SET-COMPILED-FUNCTION-NAME","mk_si_set_compiled_function_name",2},
  {"SI::" "COMPILED-FUNCTION-OWNER","mk_si_compiled_function_owner",1},
  {"SI::" "SET-COMPILED-FUNCTION-OWNER","mk_si_set_compiled_function_owner",2},

  {"SI::" "SELF-TRUENAME","mk_si_self_truename",0},

  {"MKCL::" "!",NULL,-1},

  {"SI::" "GC-OFF","mk_si_gc_off",0},
  {"SI::" "GC-ON","mk_si_gc_on",0},

  {"SI::" "TOP-APPLY","mk_si_top_apply",2},

  {"SI::" "CONVERT-CMP-LEXICAL-INFO","mk_si_convert_cmp_lexical_info",1},

  {"SI::" "INSTALL-SIGSEGV-MONITOR","mk_si_install_sigsegv_monitor",0},

  {":" "DETACHED",NULL,-1},
  {":" "IMPORTED",NULL,-1},

  {":" "FOLLOW-SYMLINKS",NULL,-1},

  {"MKCL::" "BAD-FASL-FILE",NULL,-1},
  {":" "FORMAT",NULL,-1},
  {":" "ARCHITECTURE",NULL,-1},
  {":" "OS",NULL,-1},
  {":" "STALE",NULL,-1},
  {":" "CORRUPTED",NULL,-1},

  {":" "KILLED",NULL,-1},
  {":" "KILLED-BY-DEBUGGER",NULL,-1},
  {":" "INVALID-VALUE",NULL,-1},

  {":" "READ",NULL,-1},
  {":" "WRITE",NULL,-1},

  {":" "CHANGE-DEFAULT-PATHNAME-DEFAULTS",NULL,-1},
  {":" "ALL-DRIVES",NULL,-1},
  {":" "LINENO",NULL,-1},

  {"SI::" "LIST-LIBRARIES","mk_si_list_libraries",0},

  {"SI::" "COMPILED-CLOSURE",NULL,-1},
  {"SI::" "COMPILED-CLOSURE-DISPLAY",NULL,-1},
  {"SI::" "COMPILED-CLOSURE-LEVEL",NULL,-1},
  {"SI::" "COMPILED-DEBUG-INFORMATION",NULL,-1},
  {"SI::" "CLOSURE-DEPTH","mk_si_closure_depth",1},
  {"SI::" "CLOSURE-LEVEL","mk_si_closure_level",2},
  {"SI::" "CLOSURE-LEVEL-SIZE","mk_si_closure_level_size",1},
  {"SI::" "CLOSURE-LEVEL-VAR","mk_si_closure_level_var",2},
  {"SI::" "CLOSURE-LEVEL-SET-VAR","mk_si_closure_level_set_var",3},
  {"SI::" "CLOSURE-LEVEL-OUTER-LEVEL","mk_si_closure_level_outer_level",1},
  {"SI::" "SYSTEM-PROPERTIES","mk_si_system_properties",0},
  {"SI::" "BYTECODEP","mk_si_bytecodep",1},

  {"SI::" "SET-CLASS-PROPER-NAME","mk_si_set_class_proper_name",2},

  {"MKCL::" "INVALID-SLOT",NULL,-1},

  {"SI::" "CLONE-CLOSURE","mk_si_clone_closure",-1},

  {"SI::" "UPDATE-FUNCTION-REFERENCES","mk_si_update_function_references",1},
  {"SI::" "GET-FUN-REF-SYM","mk_si_get_fun_ref_sym",2},
  {"SI::" "GENERATE-FORWARD-FUN-REF-HANDLER",NULL,-1},

  {"MT::" "+FORWARD-REFERENCE-LOCK+",NULL,-1},

  {"SI::" "OS-FILE-ERROR",NULL,-1},

  {"SI::" "DISABLE-INTERRUPTS","mk_si_disable_interrupts",0},
  {"SI::" "ENABLE-INTERRUPTS","mk_si_enable_interrupts",0},

  {"MKCL::" "GETUID","mk_mkcl_getuid",0},
  {"SI::" "GDB","mk_si_gdb",0},

  {"SI::" "*DYNAMIC-CONS-STACK*",NULL,-1},
  {"SI::" "TRIM-DYNAMIC-CONS-STACK","mk_si_trim_dynamic_cons_stack",0},
  {"SI::" "DYN-CONS","mk_si_dyn_cons",2},

  {"SI::" "DISABLE-FPE","mk_si_disable_fpe",1},
  {"SI::" "ENABLE-FPE","mk_si_enable_fpe",1},
  {"SI::" "ALL-ENABLED-FPE","mk_si_all_enabled_fpe",0},
  {"SI::" "FPE-ENABLED-P","mk_si_fpe_enabled_p",1},
  {"SI::" "ALL-RAISED-FPE","mk_si_all_raised_fpe",0},
  {"SI::" "FPE-RAISED-P","mk_si_fpe_raised_p",1},
  {"SI::" "RAISE-FPE","mk_si_raise_fpe",1},
  {"SI::" "CLEAR-FPE","mk_si_clear_fpe",1},
  {"SI::" "CLEAR-ALL-FPE","mk_si_clear_all_fpe",0},
  {"SI::" "INITIAL-FLOATING-POINT-EXCEPTION-SET","mk_si_initial_floating_point_exception_set",0},
  {"SI::" "*DEFAULT-FLOATING-POINT-EXCEPTION-SET*",NULL,-1},

  {"SI::" "OUTPUT-FLOAT",NULL,-1},
  {"SI::" "*READ-FLOAT-EXACTLY*",NULL,-1},
  {"SI::" "*PRINT-FLOAT-EXACTLY*",NULL,-1},

  {"SI::" "INDEX",NULL,-1},

  {"MKCL::" "WITH-UNIQUE-NAMES",NULL,-1},

  {"SI::" "BIT-SET",NULL,-1},
  {"SI::" "SBIT-SET",NULL,-1},

  {"SI::" "CONCATENATE-STRINGS","mk_si_concatenate_strings",-1},

  {"SI::" "SIMPLE-BASE-STRING-P","mk_si_simple_base_string_p",1},

  {"SI::" "STREAM-EXTERNAL-FORMAT-SET","mk_si_stream_external_format_set",2},
  {"SI::" "*DEFAULT-EXTERNAL-FORMAT*",NULL,-1},

  {":" "UTF-16LE",NULL,-1},
  {":" "UTF-16BE",NULL,-1},
  {":" "UTF-16",NULL,-1},
  {":" "UTF-32LE",NULL,-1},
  {":" "UTF-32BE",NULL,-1},
  {":" "UTF-32",NULL,-1},
  {":" "ASCII",NULL,-1},

  {"SI::" "OS-STREAM-ERROR",NULL,-1},
  {"SI::" "CLOSED-STREAM-ERROR",NULL,-1},

  {"SI::" "GET-BUFFERING-MODE","mk_si_get_buffering_mode",1},

  {":" "INVALID",NULL,-1},
  {":" "RUNNING",NULL,-1},
  {":" "EXITED",NULL,-1},

  {"SI::" "PROCESS",NULL,-1},
  {"SI::" "ENCODED-STRING",NULL,-1},
  {"SI::" "UTF-8","mk_si_utf_8",1},
  {"SI::" "UTF-8-P","mk_si_utf_8_p",1},
  {"SI::" "UTF-8-LENGTH","mk_si_utf_8_length",1},
  {"SI::" "UTF-8-AS-IS","mk_si_utf_8_as_is",1},
  {"SI::" "UTF-8-CHAR","mk_si_utf_8_char",2},
  {"SI::" "UTF-8+","mk_si_utf_8Plus",-1},
  {"SI::" "UTF-8=","mk_si_utf_8E",2},
  {"SI::" "UTF-8-PUSH-EXTEND","mk_si_utf_8_push_extend",2},
  {"SI::" "UTF-8-LAST","mk_si_utf_8_last",1},
  {"SI::" "UTF-16","mk_si_utf_16",1},
  {"SI::" "UTF-16-P","mk_si_utf_16_p",1},
  {"SI::" "UTF-16-LENGTH","mk_si_utf_16_length",1},
  {"SI::" "UTF-16-AS-IS","mk_si_utf_16_as_is",1},
  {"SI::" "UTF-16-CHAR","mk_si_utf_16_char",2},
  {"SI::" "UTF-16+","mk_si_utf_16Plus",2},
  {"SI::" "UTF-16=","mk_si_utf_16E",1},
  {"SI::" "UTF-16-PUSH-EXTEND","mk_si_utf_16_push_extend",2},
  {"SI::" "UTF-16-LAST","mk_si_utf_16_last",1},

  {"MT::" "JOIN-THREAD","mk_mt_thread_join",1},
  {"MT::" "DETACH-THREAD","mk_mt_thread_detach",1},
  {"MT::" "THREAD-PLIST","mk_mt_thread_plist",1},
  {"MT::" "SET-THREAD-PLIST","mk_mt_set_thread_plist",2},

  {"SI::" "JOIN-PROCESS","mk_si_join_process",1},
  {"SI::" "TERMINATE-PROCESS","mk_si_terminate_process",-1},
  {"SI::" "PROCESS-P","mk_si_process_p",1},
  {"SI::" "PROCESS-INPUT","mk_si_process_input",1},
  {"SI::" "PROCESS-OUTPUT","mk_si_process_output",1},
  {"SI::" "PROCESS-ERROR","mk_si_process_error",1},
  {"SI::" "PROCESS-PLIST","mk_si_process_plist",1},
  {"SI::" "SET-PROCESS-PLIST","mk_si_set_process_plist",2},
  {"SI::" "PROCESS-STATUS","mk_si_process_status",1},
  {"SI::" "PROCESS-EXIT-CODE","mk_si_process_exit_code",1},
  {"SI::" "PROCESS-COMMAND","mk_si_process_command",1},
  {"SI::" "PROCESS-ARGV","mk_si_process_argv",1},
  {"SI::" "PROCESS-ID","mk_si_process_id",1},
  {"SI::" "PROCESS-DETACHED-P","mk_si_process_detached_p",1},
  {"SI::" "DETACH-PROCESS","mk_si_detach_process",1},

  {"SI::" "C-GLOBAL",NULL,-1},

  {"SI::" "BYTECODE-CLOSURE",NULL,-1},

  {"SI::" "SAMPLE-ALLOCATION-STATISTICS","mk_si_sample_allocation_statistics",0},
  {"SI::" "RESET-ALLOCATION-STATISTICS","mk_si_reset_allocation_statistics",0},
  {"SI::" "ROOM-REPORT","mk_si_room_report",1},

  {"MKCL::" "SIMPLE-STYLE-WARNING",NULL,-1},
  {"MKCL::" "DOLIST!",NULL,-1},

  {"MKCL::" "PROBE-FILE-P","mk_mkcl_probe_file_p",1},
  {"MKCL::" "STREAM-FILENAME","mk_mkcl_stream_filename",1},

  {"SI::" "MANGLE-FUNCTION-NAME","mk_si_mangle_function_name",1},
  {"SI::" "MANGLE-STRING","mk_si_mangle_string",1},
  {"SI::" "MANGLE-SYMBOL","mk_si_mangle_symbol",1},

  {":" "ENCODING",NULL,-1},

  {"MKCL::" "PRIN1-TO-BASE-STRING","mk_mkcl_prin1_to_base_string",-1},
  {"MKCL::" "PRINC-TO-BASE-STRING","mk_mkcl_princ_to_base_string",-1},
  {"MKCL::" "WRITE-TO-BASE-STRING","mk_mkcl_write_to_base_string",-1},

  {"SI::" "*OS-STRING-FORMAT*",NULL,-1},

  {"SI::" "CLOSE-PACKAGE","mk_si_close_package",1},
  {"SI::" "REOPEN-PACKAGE","mk_si_reopen_package",1},
  {"SI::" "PACKAGE-CLOSED-P","mk_si_package_closed_p",1},

  {"SI::" "SIMPLE-CONTROL-ERROR",NULL,-1},
  {"SI::" "SIMPLE-PACKAGE-ERROR",NULL,-1},
  {"SI::" "SIMPLE-READER-ERROR",NULL,-1},

  {"SI::" "C-EXPORT-FNAME",NULL,-1},
  {"SI::" "NO-CHECK-TYPE",NULL,-1},

  {":" "ABORTED",NULL,-1},
  {"MT::" "ABANDON-THREAD","mk_mt_abandon_thread",1},
  {"SI::" "+SHUTDOWN-GATE+",NULL,-1},
  {"SI::" "SHUTDOWN-IN-PROGRESS-P","mk_si_shutdown_in_progress_p",0},
  {"SI::" "REGISTER-SHUTDOWN-THREAD","mk_si_register_shutdown_thread",1},
  {"SI::" "REGISTER-SHUTDOWN-WATCHDOG-THREAD","mk_si_register_shutdown_watchdog_thread",2},
  {"SI::" "SHUTDOWN-WATCHDOG-THREAD","mk_si_shutdown_watchdog_thread",0},
  {"SI::" "SHUTDOWN-MKCL","mk_si_shutdown_mkcl",4},

  {"SI::" "SETUP-FOR-GDB","mk_si_setup_for_gdb",-1},

  {"MT::" "CURRENT-THREAD","mk_mt_current_thread",0},

  {":" "FAST",NULL,-1},
  {":" "ENABLED",NULL,-1},
  {":" "DISABLED",NULL,-1},
  {"SI::" "INTERRUPT-STATUS","mk_si_interrupt_status",0},

  {"SI::" "*DRIBBLE-CLOSER*",NULL,-1},

  {"MKCL::" "STREAM-ENCODING-ERROR",NULL,-1},
  {"MKCL::" "STREAM-DECODING-ERROR",NULL,-1},
  {"SI::" "STREAM-ENCODING-ERROR","mk_si_stream_encoding_error",3},
  {"SI::" "STREAM-DECODING-ERROR","mk_si_stream_decoding_error",3},

  {"MKCL::" "BASE-CHAR-CODE-LIMIT",NULL,-1},
  {"MKCL::" "BASE-CHAR-P","mk_mkcl_base_char_p",1},

  {"SI::" "COPY-TO-SIMPLE-STRING","mk_si_copy_to_simple_string",1},

  {":" "MKCL-MIN",NULL,-1},

  {"SI::" "SCRUB-VALUES","mk_si_scrub_values",0},




  {"MT::" "CANCEL-THREAD","mk_mt_cancel_thread",0},
  {":" "CANCELED",NULL,-1},
  {":" "TERMINATED",NULL,-1},
  {"MT::" "TRY-TO-WAKE-UP-THREAD","mk_mt_try_to_wake_up_thread",1},
  {"MT::" "REQUEST-THREAD-SHUTDOWN","mk_mt_request_thread_shutdown",1},
  {"MT::" "THREAD-SHUTDOWN-REQUESTED-P","mk_mt_thread_shutdown_requested_p",1},

  {":" "SHUTDOWN",NULL,-1},
  {":" "SIGNAL-ERROR",NULL,-1},
  {":" "INTERRUPTED",NULL,-1},

  {"SI::" "MAKE-FOREIGN-NULL-POINTER","mk_si_make_foreign_null_pointer",0},
  {"SI::" "FOREIGNP","mk_si_foreignp",1},
  {"SI::" "LIBC-ERROR-STRING","mk_si_libc_error_string",1},
  {"SI::" "ERRNO-STRING","mk_si_errno_string",0},
  {"SI::" "GET-LOCAL-TIME-ZONE","mk_si_get_local_time_zone",0},
  {"SI::" "UNAME","mk_si_uname",0},

  {"MKCL::" "PATHNAME-COMPLETE-P","mk_mkcl_pathname_complete_p",1},
  {"MKCL::" "MELD-PATHNAMES","mk_mkcl_meld_pathnames",-1},
  {"MKCL::" "*CURRENT-WORKING-DIRECTORY*",NULL,-1},
  {"MKCL::" "*ALL-CURRENT-WORKING-DIRECTORIES*",NULL,-1},

  {":" "REAL-NAME",NULL,-1},
  {":" "SEARCH",NULL,-1},

  {"SI::" "NON-INTERACTIVE-THREAD-DEBUGGER-TRAP","mk_si_non_interactive_thread_debugger_trap",2},

  {"SI::" "MKCL-VERSION","mk_si_mkcl_version",0},
  {"SI::" "MKCL-MAJOR-VERSION","mk_si_mkcl_major_version",0},
  {"SI::" "MKCL-MINOR-VERSION","mk_si_mkcl_minor_version",0},
  {"SI::" "MKCL-PATCH-LEVEL","mk_si_mkcl_patch_level",0},

  {"SI::" "*RESTART-CLUSTERS*",NULL,-1},
  {"SI::" "*CONDITION-RESTARTS*",NULL,-1},
  {"SI::" "*HANDLER-CLUSTERS*",NULL,-1},

  {"SI::" "SET-BINDING-STACK-LIMIT","mk_si_set_binding_stack_limit",1},
  {"SI::" "GET-BINDING-STACK-LIMIT","mk_si_get_binding_stack_limit",0},
  {"SI::" "SET-FRAME-STACK-LIMIT","mk_si_set_frame_stack_limit",1},
  {"SI::" "GET-FRAME-STACK-LIMIT","mk_si_get_frame_stack_limit",0},
  {"SI::" "SET-LISP-TEMP-STACK-LIMIT","mk_si_set_lisp_temp_stack_limit",1},
  {"SI::" "GET-LISP-TEMP-STACK-LIMIT","mk_si_get_lisp_temp_stack_limit",0},
  {"SI::" "SET-HEAP-SIZE-LIMIT","mk_si_set_heap_size_limit",1},
  {"SI::" "GET-HEAP-SIZE-LIMIT","mk_si_get_heap_size_limit",0},
  {"SI::" "GET-CALL-STACK-LIMIT","mk_si_get_call_stack_limit",0},

  {":" "CALL-STACK-SIZE",NULL,-1},
  {":" "LISP-TEMP-STACK-INITIAL-SIZE",NULL,-1},
  {":" "LISP-TEMP-STACK-SIZE-LIMIT",NULL,-1},
  {":" "BINDING-STACK-INITIAL-SIZE",NULL,-1},
  {":" "BINDING-STACK-SIZE-LIMIT",NULL,-1},
  {":" "FRAME-STACK-INITIAL-SIZE",NULL,-1},
  {":" "FRAME-STACK-SIZE-LIMIT",NULL,-1},
  {":" "SIGALTSTACK-SIZE",NULL,-1},
  {":" "UNLIMITED",NULL,-1},

  {":" "GC-ABORT",NULL,-1},
  {":" "GC-EXIT",NULL,-1},

  {":" "ACTIVE",NULL,-1},
  {":" "SET",NULL,-1},
  {":" "INITIALIZED",NULL,-1},
  {":" "DONE",NULL,-1},
  {":" "UNKNOWN",NULL,-1},
  {"MT::" "THREAD-STATUS","mk_mt_thread_status",1},

  {"CLOS::" "*REDEFINE-CLASS-IN-PLACE*",NULL,-1},

  {":" "FOREIGN",NULL,-1},
  {"SI::" "TRIM-FFI-ARGUMENTS-STAGING-AREA","mk_si_trim_ffi_arguments_staging_area",0},
  {"SI::" "RELEASE-FFI-AREA","mk_si_release_ffi_area",0},

  {"SI::" "LIST-ALL-CHILDREN","mk_si_list_all_children",0},
  {"SI::" "TRACE-SPECIALS","mk_si_trace_specials",0},
  {"SI::" "UNTRACE-SPECIALS","mk_si_untrace_specials",0},

  {"MT::" "ABORT-THREAD","mk_mt_abort_thread",0},

  {"MKCL::" "NATURAL8",NULL,-1},
  {"MKCL::" "NATURAL16",NULL,-1},
  {"MKCL::" "NATURAL32",NULL,-1},
  {"MKCL::" "NATURAL64",NULL,-1},
  {"MKCL::" "OCTET",NULL,-1},
  {"MKCL::" "DOUBLE-OCTET",NULL,-1},
  {"MKCL::" "OCTETS","mk_mkcl_octets",1},
  {"MKCL::" "DOUBLE-OCTETS","mk_mkcl_double_octets",1},
# 2089 "symbols_list.h"
  {NULL,NULL,-1}};
